import './icon.css';
import * as React from 'react';
import * as Common from './common';
import {Tooltip} from './tooltip';

/* 
    Liste complète des Icons: 
    https://fonts.google.com/icons?icon.set=Material+Icons 
    https://github.com/google/material-design-icons/tree/master/font
*/

export enum EIcon {
    /*Action*/
    SEARCH  = 'search',
    HOME  = 'home',
    ACCOUNT_CIRCLE = 'account_circle',
    SETTINGS = 'settings',
    DONE = 'done',
    INFO = 'info',
    CHECK_CIRCLE = 'check_circle',
    DELETE = 'delete',
    SHOPPING_CART = 'shopping_cart',
    VISIBILITY = 'visibility',
    FAVORITE = 'favorite',

    LOGOUT = 'logout',
    DESCRIPTION = 'description',
    FAVORITE_BORDER = 'favorite_border',
    LOCK = 'lock',
    SCHEDULE = 'schedule',
    LANGUAGE = 'language',
    FACE = 'face',
    HELP_OUTLINE = 'help_outline',
    MANAGE_ACCOUNTS = 'manage_accounts',
    FILTER_ALT = 'filter_alt',
    FINGERPRINT = 'fingerprint',

    EVENT = 'event',
    VERIFIED = 'verified',
    THUMB_UP = 'thumb_up',
    DASHBOARD = 'dashboard',
    LOGIN = 'login',
    CALENDAR_TODAY = 'calendar_today',
    VISIBILITY_OFF = 'visibility_off',
    LIST = 'list',
    CHECK_CIRCLE_OUTLINE = 'check_circle_outline',
    HIGHLIGHT_OFF = 'highlight_off',
    HELP = 'help',

    DATE_RANGE = 'date_range',
    QUESTION_ANSWER = 'question_answer',
    TASK_ALT = 'task_alt',
    PAID = 'paid',
    ARTICLE = 'article',
    SHOPPING_BAG = 'shopping_bag',
    LIGHTBULB = 'lightbulb',
    OPEN_IN_NEW = 'open_in_new',
    PERM_IDENTITY = 'perm_identity',
    TRENDING_UP = 'trending_up',
    HISTORY = 'history',

    CREDIT_CARD = 'credit_card',
    ACCOUNT_BALANCE = 'account_balance',
    DELETE_OUTLINE = 'delete_outline',
    REPORT_PROBLEM = 'report_problem',
    FACT_CHECK = 'fact_check',
    ASSIGNMENT = 'assignment',
    VERIFIED_USER = 'verified_user',
    ARROW_RIGHT_ALT = 'arrow_right_alt',
    STAR_RATE = 'star_rate',
    ACCOUNT_BALANCE_WALLER = 'account_balance_wallet',
    ANALYTICS = 'analytics',

    AUTORENEW = 'autorenew',
    WORK = 'work',
    BUILD = 'build',
    VIEW_LIST = 'view_list',
    PRINT = 'print',
    STORE = 'store',
    TODAY = 'today',
    DELETE_FOREVER = 'delete_forever',
    ADMIN_PANEL_SETTINGS = 'admin_panel_settings',
    LOCK_OPEN = 'lock_open',
    ROOM = 'room',

    SAVINGS = 'savings',
    CODE = 'code',
    GRADE = 'grade',
    RECEIPT = 'receipt',
    WATCH_LATER = 'watch_later',
    UPDATE = 'update',
    ADD_SHOPPING_CART = 'add_shopping_cart',
    CONTACT_SUPPORT = 'contact_support',
    POWER_SETTING_NEW = 'power_settings_new',
    PETS = 'pets',
    DONE_ALL = 'done_all',

    EXPLORE = 'explore',
    BOOKMARK = 'bookmark',
    BOOKMARK_BORDER = 'bookmark_border',
    NOTE_ADD = 'note_add',
    REORDER = 'reorder',
    ACCOUNT_BOX = 'account_box',
    SHOPPING_BASKET = 'shopping_basket',
    PENDING_ACTIONS = 'pending_actions',
    DRAG_INDICATOR = 'drag_indicator',
    PAYMENT = 'payment',
    CALENDAR_MONTH = 'calendar_month',

    LAUNCH = 'launch',
    SUPERVISOR_ACCOUNT = 'supervisor_account',
    PENDING = 'pending',
    ZOOM_IN = 'zoom_in',
    TOUCH_APP = 'touch_app',
    ASSESSMENT = 'assessment',
    THUMB_UP_OFF_ALT = 'thumb_up_off_alt',
    OPEN_IN_FULL = 'open_in_full',
    LEADERBOARD = 'leaderboard',
    DONE_OUTLINE = 'done_outline',
    EXIT_TO_APP = 'exit_to_app',

    PREVIEW = 'preview',
    ASSIGNMENT_IND = 'assignment_ind',
    CARD_GIFTCARD = 'card_giftcard',
    VIEW_IN_AR = 'view_in_ar',
    WORK_OUTNLINE = 'work_outline',
    PUBLISHED_WITH_CHANGES = 'published_with_changes',
    FEEDBACK = 'feedback',
    TIMELINE = 'timeline',
    DSN = 'dns',
    SWAP_HORIZ = 'swap_horiz',
    SYNCH_ALT = 'sync_alt',

    ASSIGNMENT_TURNED_IN = 'assignment_turned_in',
    FLIGHT_TAKEOFF = 'flight_takeoff',
    STARS = 'stars',
    BOOK = 'book',
    LABEL = 'label',
    PAN_TOOL = 'pan_tool',
    BUG_REPORT = 'bug_report',
    CONTACT_PAGE = 'contact_page',
    GAVEL = 'gavel',
    CACHED = 'cached',
    ALARM = 'alarm',
    
    TRANSLATE = 'translate',
    SPACE_DASHBOARD = 'space_dashboard',
    ANDROID = 'android',
    SUPERVISED_USER_CIRCLE = 'supervised_user_circle',
    EDIT_CALENDAR = 'edit_calendar',
    ACCESSIBILITY = 'accessibility',
    MINIMIZE = 'minimize',
    EXTENSION = 'extension',
    GET_APP = 'get_app',
    TIPS_AND_UPDATES = 'tips_and_updates',
    RECORD_VOICE_OVER = 'record_voice_over',
    
    ADD_TASK = 'add_task',
    TRENDING_FLAT = 'trending_flat',
    HOURGLASS_EMPTY = 'hourglass_empty',
    HELP_CENTER = 'help_center',
    THUMB_DOWN = 'thumb_down',
    ACCESSIBILITY_NEW = 'accessibility_new',
    STICKY_NOTE_2 = 'sticky_note_2',
    RULE = 'rule',
    DASHBOARD_CUSTOMIZE = 'dashboard_customize',
    SOURCE = 'source',
    
    SUPPORT = 'support',
    FIND_IN_PAGE = 'find_in_page',
    CLOSE_FULLSCREEN = 'close_fullscreen',
    SETTINGS_APPLICATIONS = 'settings_applications',
    REDEEM = 'redeem',
    VIEW_HEADLINE = 'view_headline',
    ANNOUNCEMENT = 'announcement',
    LOYALTY = 'loyalty',
    ADS_CLICK = 'ads_click',
    GROUP_WORK = 'group_work',
    SWAP_VERT = 'swap_vert',
    
    RESTORE = 'restore',
    EURO_SYMBOL = 'euro_symbol',
    SENSORS = 'sensors',
    DANGEROUS = 'dangerous',
    COMPARE_ARROWS = 'compare_arrows',
    ROCKET_LAUNCH = 'rocket_launch',
    NIGHTLIGHT_ROUND = 'nightlight_round',
    QUESTION_MARK = 'question_mark',
    PRIVACY_TIP = 'privacy_tip',
    ARROW_CIRCLE_RIGHT = 'arrow_circle_right',
    SUBJECT = 'subject',
    
    DISABLED_BY_DEFAULT = 'disabled_by_default',
    TRACK_CHANGES = 'track_changes',
    TABLE_VIEW = 'table_view',
    HTTPS = 'https',
    GRADING = 'grading',
    COPYRIGHT = 'copyright',
    TOC = 'toc',
    ARROW_CIRCLE_UP = 'arrow_circle_up',
    BOOKMARKS = 'bookmarks',
    API = 'api',
    QUERY_BUILDER = 'query_builder',
    
    PERM_MEDIA = 'perm_media',
    BUILD_CIRCLE = 'build_circle',
    INPUT = 'input',
    ZOOM_OUT = 'zoom_out',
    BOOK_ONLINE = 'book_online',
    BACKUP = 'backup',
    PERM_CONTACT_CALENDAR = 'perm_contact_calendar',
    VIEW_MODULE = 'view_module',
    OPEN_WITH = 'open_with',
    SETTINGS_PHONE = 'settings_phone',
    CIRCLE_NOTIFICATIONS = 'circle_notifications',
    
    SPEAKER_NOTES = 'speaker_notes',
    ROTATION_3D = '3d_rotation',
    ARROW_CIRCLE_DOWN = 'arrow_circle_down',
    LABEL_IMPORTANT = 'label_important',
    CARD_MEMBERSHIP = 'card_membership',
    PERM_PHONE_MSG = 'perm_phone_msg',
    FILE_PRESENT = 'file_present',
    WYSIWYG = 'wysiwyg',
    PAGEVIEW = 'pageview',
    SWIPE = 'swipe',
    INTEGRATION_INSTRUCTIONS = 'integration_instructions',
    
    UPGRADE = 'upgrade',
    TRENDING_DOWN = 'trending_down',
    CHANGE_HISTORY = 'change_history',
    CLASS = 'class',
    ACCESSIBLE = 'accessible',
    G_TRANSLATE = 'g_translate',
    SETTINGS_ACCESSIBILITY = 'settings_accessibility',
    PRODUCTION_QUANTITY_LIMITS = 'production_quantity_limits',
    OFFLINE_BOLT = 'offline_bolt',
    EXPAND = 'expand',
    MODEL_TRAINING = 'model_training',
    
    DONUT_LARGE = 'donut_large',
    ASPECT_RATIO = 'aspect_ratio',
    CALENDAR_VIEW_MONTH = 'calendar_view_month',
    SETTINGS_BACKUP_RESTORE = 'settings_backup_restore',
    SEGMENT = 'segment',
    VIEW_COLUMN = 'view_column',
    SCHEDULE_SEND = 'schedule_send',
    MAXIMIZE = 'maximize',
    BOOKMARK_ADD = 'bookmark_add',
    ARROW_CIRCLE_LEFT = 'arrow_circle_left',
    THUMBS_UP_DOWN = 'thumbs_up_down',
    
    ALARM_ON = 'alarm_on',
    PERCENT = 'percent',
    THUMB_DOWN_OFF_ALT = 'thumb_down_off_alt',
    SETTINGS_ETHERNET = 'settings_ethernet',
    VIEW_AGENDA = 'view_agenda',
    THEATERS = 'theaters',
    IMPORTANT_DEVICES = 'important_devices',
    INVERT_COLORS = 'invert_colors',
    CURRENCY_EXCHANGE = 'currency_exchange',
    UNPUBLISHED = 'unpublished',
    OPEN_IN_BROWSER = 'open_in_browser',
    
    COMMUTE = 'commute',
    OPACITY = 'opacity',
    ADDCHART = 'addchart',
    NO_ACCOUNTS = 'no_accounts',
    YOUTUBE_SEARCHED_FOR = 'youtube_searched_for',
    HISTORY_TOGGLE_OFF = 'history_toggle_off',
    VIEW_WEEK = 'view_week',
    TOUR = 'tour',
    SYSTEM_UPDATE_ALT = 'system_update_alt',
    SETTINGS_INPUT_ANTENNA = 'settings_input_antenna',
    SHOP = 'shop',
    
    TURNED_IN = 'turned_in',
    MARK_AS_UNREAD = 'mark_as_unread',
    BOOKMARK_ADDED = 'bookmark_added',
    HIDE_SOURCE = 'hide_source',
    PLAGIARISM = 'plagiarism',
    FLIGHT_LAND = 'flight_land',
    SEARCH_OFF = 'search_off',
    NOT_STARTED = 'not_started',
    CONTACTLESS = 'contactless',
    SAVED_SEARCH = 'saved_search',
    ASSIGNMENT_LATE = 'assignment_late',
    
    DONUT_SMALL = 'donut_small',
    HIGHLIGHT_ALT = 'highlight_alt',
    TURNED_IN_NOT = 'turned_in_not',
    VIEW_CAROUSEL = 'view_carousel',
    ANCHOR = 'anchor',
    SETTINGS_INPUT_COMPONENT = 'settings_input_component',
    MEDIATION = 'mediation',
    FIT_SCREEN = 'fit_screen',
    ASSIGNMENT_RETURN = 'assignment_return',
    TOLL = 'toll',
    FLAKY = 'flaky',
    
    EDIT_OFF = 'edit_off',
    REMOVE_SHOPPING_CART = 'remove_shopping_cart',
    VIEW_QUILT = 'view_quilt',
    SETTINGS_REMOTE = 'settings_remote',
    ALL_INBOX = 'all_inbox',
    HOURGLASS_FULL = 'hourglass_full',
    LOCK_CLOCK = 'lock_clock',
    SETTINGS_VOICE = 'settings_voice',
    PREGNANT_WOMAN = 'pregnant_woman',
    ONLINE_PREDICTION = 'online_prediction',
    HOTEL_CLASS = 'hotel_class',
    
    SWAP_HORIZONTAL_CIRCLE = 'swap_horizontal_circle',
    EVENT_SEAT = 'event_seat',
    VIEW_SIDEBAR = 'view_sidebar',
    NEXT_PLAN = 'next_plan',
    CAMERA_ENHANCE = 'camera_enhance',
    MARKUNREAD_MAILBOX = 'markunread_mailbox',
    VERTICAL_SPLIT = 'vertical_split',
    RESTORE_FROM_TRASH = 'restore_from_trash',
    BALANCE = 'balance',
    DYNAMIC_FORM = 'dynamic_form',
    ACCESSIBLE_FORWARD = 'accessible_forward',
    
    CALENDAR_VIEW_WEEK = 'calendar_view_week',
    TAB = 'tab',
    SHOPPING_CART_CHECKOUT = 'shopping_cart_checkout',
    FILTER_ALT_OFF = 'filter_alt_off',
    DATA_EXPLORATION = 'data_exploration',
    ADD_TO_DRIVE = 'add_to_drive',
    VIEW_STREAM = 'view_stream',
    SETTINGS_POWER = 'settings_power',
    REMOVE_DONE = 'remove_done',
    SMART_BUTTON = 'smart_button',
    REQUEST_PAGE = 'request_page',
    
    CARD_TRAVEL = 'card_travel',
    TRY = 'try',
    OFFLINE_PIN = 'offline_pin',
    OUTBOX = 'outbox',
    ROWING = 'rowing',
    CALENDAR_VIEW_DAY = 'calendar_view_day',
    OUTLET = 'outlet',
    ROCKET = 'rocket',
    FIND_REPLACE = 'find_replace',
    TOKEN = 'token',
    COMPRESS = 'compress',
    
    CHROME_READER_MODE = 'chrome_reader_mode',
    SETTINGS_BRIGHTNESS = 'settings_brightness',
    HTTP = 'http',
    ALARM_ADD = 'alarm_add',
    ASSIGNMENT_RETURNED = 'assignment_returned',
    SPELLCHECK = 'spellcheck',
    PLAY_FOR_WORK = 'play_for_work',
    BACKUP_TABLE = 'backup_table',
    GIF = 'gif',
    RESTORE_PAGE = 'restore_page',
    CREDIT_CARD_OFF = 'credit_card_off',
    
    WIFI_PROTECTED_SETUP = 'wifi_protected_setup',
    SETTINGS_OVERSCAN = 'settings_overscan',
    LOCK_RESET = 'lock_reset',
    NEW_LABEL = 'new_label',
    FAX = 'fax',
    TERMINAL = 'terminal',
    GENERATING_TOKENS = 'generating_tokens',
    SETTINGS_INPUT_COMPOSITE = 'settings_input_composite',
    QUICKREPLY = 'quickreply',
    COMMENT_BANK = 'comment_bank',
    VIEW_DAY = 'view_day',
    
    SWAP_VERTICAL_CIRCLE = 'swap_vertical_circle',
    POLYMER = 'polymer',
    OUTBOUND = 'outbound',
    LINE_WEIGHT = 'line_weight',
    CANCEL_SCHEDULE_SEND = 'cancel_schedule_send',
    HORIZONTAL_SPLIT = 'horizontal_split',
    BATCH_PREDICTION = 'batch_prediction',
    SEND_AND_ARCHIVE = 'send_and_archive',
    FREE_CANCELLATION = 'free_cancellation',
    PICTURE_IN_PICTURE = 'picture_in_picture',
    DENSITY_MEDIUM = 'density_medium',
    
    CODE_OFF = 'code_off',
    DISABLED_VISIBLE = 'disabled_visible',
    BOOKMARK_REMOVE = 'bookmark_remove',
    SETTINGS_BLUETOOTH = 'settings_bluetooth',
    SWITCH_ACCESS_SHORTCUT = 'switch_access_shortcut',
    FLIP_TO_FRONT = 'flip_to_front',
    SHOP_TWO = 'shop_two',
    ADD_CARD = 'add_card',
    GIF_BOX = 'gif_box',
    SATELLITE_ALT = 'satellite_alt',
    EJECT = 'eject',
    
    SPEAKER_NOTES_OFF = 'speaker_notes_off',
    VIEW_TIMELINE = 'view_timeline',
    PERM_DATA_SETTING = 'perm_data_setting',
    SETTINGS_INPUT_HDMI = 'settings_input_hdmi',
    PERM_SCAN_WIFI = 'perm_scan_wifi',
    ALARM_OFF = 'alarm_off',
    SETTINGS_CELL = 'settings_cell',
    HOURGLASS_DISABLED = 'hourglass_disabled',
    APP_BLOCKING = 'app_blocking',
    SENSORS_OFF = 'sensors_off',
    
    WORK_OFF = 'work_off',
    ASSURED_WORKLOAD = 'assured_workload',
    LINE_STYLE = 'line_style',
    ONE_TWO_THREE = '123',
    HTML = 'html',
    PICTURE_IN_PICTURE_ALT = 'picture_in_picture_alt',
    PERM_DEVICE_INFORMATION = 'perm_device_information',
    SWITCH_ACCESS_SHORTCUT_ADD = 'switch_access_shortcut_add',
    SUBTITLES_OFF = 'subtitles_off',
    DISPLAY_SETTINGS = 'display_settings',
    EVENT_REPEAT = 'event_repeat',
    
    UPDATE_DISABLED = 'update_disabled',
    OUTPUT = 'output',
    SETTINGS_INPUT_SVIDEO = 'settings_input_svideo',
    VOICE_OVER_OFF = 'voice_over_off',
    NOISE_CONTROL_OFF = 'noise_control_off',
    FLIP_TO_BACK = 'flip_to_back',
    VIEW_ARRAY = 'view_array',
    WORK_HISTORY = 'work_history',
    OPEN_IN_NEW_OFF = 'open_in_new_off',
    SWIPE_LEFT = 'swipe_left',
    ALL_OUT = 'all_out',
    
    JAVASCRIPT = 'javascript',
    PRIVATE_CONNECTIVITY = 'private_connectivity',
    APP_SHORTCUT = 'app_shortcut',
    JOIN_FULL = 'join_full',
    LABEL_OFF = 'label_off',
    ROUNDED_CORNER = 'rounded_corner',
    TAB_UNSELECTED = 'tab_unselected',
    PAN_TOOL_ALT = 'pan_tool_alt',
    SHOP_2 = 'shop_2',
    TEXT_ROTATE_VERTICAL = 'text_rotate_vertical',
    SWIPE_RIGHT = 'swipe_right',
    
    ABC = 'abc',
    EXPLORE_OFF = 'explore_off',
    MANAGE_HISTORY = 'manage_history',
    INSTALL_DESKTOP = 'install_desktop',
    TEXT_ROTATION_NONE = 'text_rotation_none',
    SWIPE_UP = 'swipe_up',
    NOT_ACCESSIBLE = 'not_accessible',
    JOIN_INNER = 'join_inner',
    PIN_INVOKE = 'pin_invoke',
    PERM_CAMERA_MIC = 'perm_camera_mic',
    DENSITY_SMALL = 'density_small',
    
    EXTENSION_OFF = 'extension_off',
    LIGHTBULB_CIRCLE = 'lightbulb_circle',
    DATA_THRESHOLDING = 'data_thresholding',
    COMMIT = 'commit',
    INSTALL_MOBILE = 'install_mobile',
    PIN_END = 'pin_end',
    SWIPE_DOWN = 'swipe_down',
    CSS = 'css',
    TEXT_ROTATE_UP = 'text_rotate_up',
    JOIN_LEFT = 'join_left',
    VIEW_KANBAN = 'view_kanban',
    
    TEXT_ROTATION_DOWN = 'text_rotation_down',
    TEXT_ROTATION_ANGLEDOWN = 'text_rotation_angledown',
    PINCH = 'pinch',
    TEXT_ROTATION_ANGLEUP = 'text_rotation_angleup',
    SWIPE_VERTICAL = 'swipe_vertical',
    VIEW_COZY = 'view_cozy',
    JOIN_RIGHT = 'join_right',
    SWIPE_RIGHT_ALT = 'swipe_right_alt',
    VIEW_COMFY_ALT = 'view_comfy_alt',
    SPATIAL_AUDIO_OFF = 'spatial_audio_off',
    NOISE_AWARE = 'noise_aware',
    
    PHP = 'php',
    VIEW_COMPACT_ALT = 'view_compact_alt',
    SWIPE_DOWN_ALT = 'swipe_down_alt',
    BROWSE_GALLERY = 'browse_gallery',
    SWIPE_LEFT_ALT = 'swipe_left_alt',
    NETWORK_PING = 'network_ping',
    SWIPE_UP_ALT = 'swipe_up_alt',
    DENSITY_LARGE = 'density_large',
    LOCK_PERSON = 'lock_person',
    ON_DEVICE_TRAINING = 'on_device_training',
    TROUBLESHOOT = 'troubleshoot',
    
    SPATIAL_TRACKING = 'spatial_tracking',
    SPATIAL_AUDIO = 'spatial_audio',
    HLS = 'hls',
    HLS_OFF = 'hls_off',
    ARROW_OUTWARD = 'arrow_outward',
    WIDTH_NORMAL = 'width_normal',
    WIDTH_FULL = 'width_full',
    WIDTH_WIDE = 'width_wide',
    FACE_UNLOCK = 'face_unlock',
    ADD_HOME = 'add_home',
    UNFOLD_MORE_DOUBLE = 'unfold_more_double',
    
    UNFOLD_LESS_DOUBLE = 'unfold_less_double',
    REPARTITION = 'repartition',
    TRANSCRIBE = 'transcribe',
    
    /* Navigation */
    CLOSE = 'close',
    MENU = 'menu',
    EXPAND_MORE = 'expand_more',
    ARROW_BACK = 'arrow_back',
    CHEVRON_RIGHT = 'chevron_right',
    ARROW_FORWARD_IOS = 'arrow_forward_ios',
    ARROW_BACK_IOS = 'arrow_back_ios',
    ARROW_DROP_DOWN = 'arrow_drop_down',
    CANCEL = 'cancel',
    MORE_VERT = 'more_vert',
    ARROW_FORWARD = 'arrow_forward',
    
    CHEVRON_LEFT = 'chevron_left',
    CHECK = 'check',
    EXPAND_LESS = 'expand_less',
    MORE_HORIZ = 'more_horiz',
    REFRESH = 'refresh',
    APPS = 'apps',
    PAYMENTS = 'payments',
    ARROW_UPWARD = 'arrow_upward',
    EAST = 'east',
    CAMPAIGN = 'campaign',
    ARROW_BACK_IOS_NEW = 'arrow_back_ios_new',
    
    ARROW_DOWNWARD = 'arrow_downward',
    ARROW_RIGHT = 'arrow_right',
    MENU_OPEN = 'menu_open',
    FULLSCREEN = 'fullscreen',
    DOUBLE_ARROW = 'double_arrow',
    UNFOLD_MORE = 'unfold_more',
    ARROW_DROP_UP = 'arrow_drop_up',
    MAPS_HOME_WORK = 'maps_home_work',
    WEST = 'west',
    ARROW_LEFT = 'arrow_left',
    SOUTH = 'south',
    
    EXPAND_CIRCLE_DOWN = 'expand_circle_down',
    NORTH = 'north',
    NORTH_EAST = 'north_east',
    HOME_WORK = 'home_work',
    FIRST_PAGE = 'first_page',
    FULLSCREEN_EXIT = 'fullscreen_exit',
    ARROW_DROP_DOWN_CIRCLE = 'arrow_drop_down_circle',
    LAST_PAGE = 'last_page',
    UNFOLD_LESS = 'unfold_less',
    SUBDIRECTORY_ARROW_RIGHT = 'subdirectory_arrow_right',
    LEGEND_TOGGLE = 'legend_toggle',
    
    SOUTH_EAST = 'south_east',
    APP_SETTINGS_ALT = 'app_settings_alt',
    ASSISTANT_DIRECTION = 'assistant_direction',
    SUBDIRECTORY_ARROW_LEFT = 'subdirectory_arrow_left',
    NORTH_WEST = 'north_west',
    SWITCH_LEFT = 'switch_left',
    WATERFALL_CHART = 'waterfall_chart',
    SOUTH_WEST = 'south_west',
    SWITCH_RIGHT = 'switch_right',
    PIVOT_TABLE_CHART = 'pivot_table_chart',
    APPS_OUTAGE = 'apps_outage',
    OFFLINE_SHARE = 'offline_share',
    ADD_HOME_WORK = 'add_home_work',
    
    /* Maps */
    LOCAL_SHIPPING = 'local_shipping',
    PLACE = 'place',
    MENU_BOOK = 'menu_book',
    LOCAL_OFFER = 'local_offer',
    MAP = 'map',
    BADGE = 'badge',
    CATEGORY = 'category',
    RESTAURANT = 'restaurant',
    DIRECTIONS_CAR = 'directions_car',
    VOLUNTEER_ACTIVISM = 'volunteer_activism',
    LOCAL_FIRE_DEPARTMENT = 'local_fire_department',
    
    MY_LOCATION = 'my_location',
    LOCAL_MALL = 'local_mall',
    FLIGHT = 'flight',
    NEAR_ME = 'near_me',
    HANDYMAN = 'handyman',
    DIRECTIONS_RUN = 'directions_run',
    RESTAURANT_MENU = 'restaurant_menu',
    LAYERS = 'layers',
    MEDICAL_SERVICES = 'medical_services',
    LUNCH_DINING = 'lunch_dining',
    LOCAL_HOSPITAL = 'local_hospital',
    
    DIRECTIONS_WALK = 'directions_walk',
    PARK = 'park',
    CELEBRATION = 'celebration',
    PIN_DROP = 'pin_drop',
    LOCAL_LIBRARY = 'local_library',
    LOCAL_ATM = 'local_atm',
    LOCAL_ACTIVITY = 'local_activity',
    LOCAL_CAFE = 'local_cafe',
    RATE_REVIEW = 'rate_review',
    DELIVERY_DINING = 'delivery_dining',
    PERSON_PIN = 'person_pin',
    
    DESIGN_SERVICES = 'design_services',
    DIRECTIONS_BIKE = 'directions_bike',
    FASTFOOD = 'fastfood',
    DIRECTIONS_BUS = 'directions_bus',
    LOCAL_POLICE = 'local_police',
    DIRECTIONS_CAR_FILLED = 'directions_car_filled',
    HOME_REPAIR_SERVICE = 'home_repair_service',
    ZOOM_OUT_MAP = 'zoom_out_map',
    LOCAL_PHONE = 'local_phone',
    LOCAL_GROCERY_STORE = 'local_grocery_store',
    MISCELLANEOUS_SERVICES = 'miscellaneous_services',
    
    HOTEL = 'hotel',
    CLEANING_SERVICES = 'cleaning_services',
    NAVIGATION = 'navigation',
    PERSON_PIN_CIRCLE = 'person_pin_circle',
    LOCAL_GAS_STATION = 'local_gas_station',
    LOCAL_FLORIST = 'local_florist',
    LOCAL_PARKING = 'local_parking',
    TRAIN = 'train',
    DIRECTIONS = 'directions',
    LOCAL_POST_OFFICE = 'local_post_office',
    MONEY = 'money',
    
    TWO_WHEELER = 'two_wheeler',
    ELECTRICAL_SERVICES = 'electrical_services',
    TRAFFIC = 'traffic',
    LOCAL_BAR = 'local_bar',
    ALT_ROUTE = 'alt_route',
    DIAMOND = 'diamond',
    ADD_BUSINESS = 'add_business',
    PEDAL_BIKE = 'pedal_bike',
    DIRECTIONS_BOAT = 'directions_boat',
    AGRICULTURE = 'agriculture',
    BEENHERE = 'beenhere',
    
    TROIS_CENT_SOIXANTE = '360',
    LIQUOR = 'liquor',
    ROUTE = 'route',
    MOVING = 'moving',
    LOCAL_AIRPORT = 'local_airport',
    SAILING = 'sailing',
    MAPS_UGC = 'maps_ugc',
    ADD_LOCATION_ALT = 'add_location_alt',
    LOCAL_DINING = 'local_dining',
    RAMEN_DINING = 'ramen_dining',
    FACTORY = 'factory',
    
    LOCAL_TAXI = 'local_taxi',
    HAIL = 'hail',
    LOCAL_DRINK = 'local_drink',
    LOCAL_PIZZA = 'local_pizza',
    EMERGENCY = 'emergency',
    LOCAL_PRINTSHOP = 'local_printshop',
    TRIP_ORIGIN = 'trip_origin',
    THEATER_COMEDY = 'theater_comedy',
    LOCAL_LAUNDRY_SERVICE = 'local_laundry_service',
    NOT_LISTED_LOCATION = 'not_listed_location',
    WAREHOUSE = 'warehouse',
    
    DIRECTIONS_BUS_FILLED = 'directions_bus_filled',
    DINNER_DINING = 'dinner_dining',
    ADD_LOCATION = 'add_location',
    BAKERY_DINING = 'bakery_dining',
    TRANSFER_WITHIN_A_STATION = 'transfer_within_a_station',
    MULTIPLE_STOP = 'multiple_stop',
    WINE_BAR = 'wine_bar',
    TERRAIN = 'terrain',
    TAKEOUT_DINING = 'takeout_dining',
    ICECREAM = 'icecream',
    LOCAL_PHARMACY = 'local_pharmacy',
    
    STORE_MALL_DIRECTORY = 'store_mall_directory',
    MUSEUM = 'museum',
    NIGHTLIFE = 'nightlife',
    ADD_ROAD = 'add_road',
    SET_MEAL = 'set_meal',
    LOCAL_SEE = 'local_see',
    DEPARTURE_BOARD = 'departure_board',
    HARDWARE = 'hardware',
    FOREST = 'forest',
    EV_STATION = 'ev_station',
    ELECTRIC_CAR = 'electric_car',
    
    PLUMBING = 'plumbing',
    FESTIVAL = 'festival',
    CAR_RENTAL = 'car_rental',
    EDIT_LOCATION = 'edit_location',
    ATTRACTIONS = 'attractions',
    LAYERS_CLEAR = 'layers_clear',
    LOCAL_CONVENIENCE_STORE = 'local_convenience_store',
    EDIT_ROAD = 'edit_road',
    RUN_CIRCLE = 'run_circle',
    PEST_CONTROL = 'pest_control',
    DRY_CLEANING = 'dry_cleaning',
    
    EDIT_LOCATION_ALT = 'edit_location_alt',
    MOPED = 'moped',
    EDIT_ATTRIBUTES = 'edit_attributes',
    WRONG_LOCATION = 'wrong_location',
    CAR_REPAIR = 'car_repair',
    LOCAL_MOVIES = 'local_movies',
    SATELLITE = 'satellite',
    CHURCH = 'church',
    DIRECTIONS_BOAT_FILLED = 'directions_boat_filled',
    ZOOM_IN_MAP = 'zoom_in_map',
    BREAKFAST_DINING = 'breakfast_dining',
    
    TAXI_ALERT = 'taxi_alert',
    TRAM = 'tram',
    ATM = 'atm',
    TRANSIT_ENTEREXIT = 'transit_enterexit',
    SUBWAY = 'subway',
    BRUNCH_DINING = 'brunch_dining',
    SOUP_KITCHEN = 'soup_kitchen',
    ELECTRIC_BIKE = 'electric_bike',
    HVAC = 'hvac',
    ELECTRIC_SCOOTER = 'electric_scooter',
    DIRECTIONS_TRANSIT = 'directions_transit',
    
    BUS_ALERT = 'bus_alert',
    LOCAL_CAR_WASH = 'local_car_wash',
    SIGNPOST = 'signpost',
    LOCAL_HOTEL = 'local_hotel',
    MEDICAL_INFORMATION = 'medical_information',
    STREETVIEW = 'streetview',
    EGG = 'egg',
    MERGE = 'merge',
    MODE_OF_TRAVEL = 'mode_of_travel',
    CASTLE = 'castle',
    STRAIGHT = 'straight',
    
    CONNECTING_AIRPORTS = 'connecting_airports',
    COMPASS_CALIBRATION = 'compass_calibration',
    DIRECTIONS_SUBWAY = 'directions_subway',
    ELECTRIC_RICKSHAW = 'electric_rickshaw',
    DIRECTIONS_RAILWAY = 'directions_railway',
    ELECTRIC_MOPED = 'electric_moped',
    MOSQUE = 'mosque',
    NO_MEALS = 'no_meals',
    RAILWAY_ALERT = 'railway_alert',
    STADIUM = 'stadium',
    AIRLINE_STOPS = 'airline_stops',
    
    LOCAL_PLAY = 'local_play',
    BIKE_SCOOTER = 'bike_scooter',
    PEST_CONTROL_RODENT = 'pest_control_rodent',
    NEAR_ME_DISABLED = 'near_me_disabled',
    SNOWMOBILE = 'snowmobile',
    DIRECTIONS_TRANSIT_FILLED = 'directions_transit_filled',
    TURN_RIGHT = 'turn_right',
    NO_TRANSFER = 'no_transfer',
    AIRLINES = 'airlines',
    CAR_CRASH = 'car_crash',
    DIRECTIONS_SUBWAY_FILLED = 'directions_subway_filled',
    
    DIRECTIONS_RAILWAY_FILLED = 'directions_railway_filled',
    CRISIS_ALERT = 'crisis_alert',
    EGG_ALT = 'egg_alt',
    FORK_RIGHT = 'fork_right',
    SAFETY_CHECK = 'safety_check',
    TEMPLE_BUDDHIST = 'temple_buddhist',
    FLIGHT_CLASS = 'flight_class',
    TURN_LEFT = 'turn_left',
    FORT = 'fort',
    U_TURN_LEFT = 'u_turn_left',
    KEBAB_DINING = 'kebab_dining',
    
    TEMPLE_HINDU = 'temple_hindu',
    SYNAGOGUE = 'synagogue',
    TIRE_REPAIR = 'tire_repair',
    EMERGENCY_SHARE = 'emergency_share',
    U_TURN_RIGHT = 'u_turn_right',
    TURN_SHARP_RIGHT = 'turn_sharp_right',
    FORK_LEFT = 'fork_left',
    ROUNDABOUT_RIGHT = 'roundabout_right',
    TURN_SLIGHT_LEFT = 'turn_slight_left',
    SOS = 'sos',
    TURN_SLIGHT_RIGHT = 'turn_slight_right',
    
    REMOVE_ROAD = 'remove_road',
    NO_CRASH = 'no_crash',
    MINOR_CRASH = 'minor_crash',
    TURN_SHARP_LEFT = 'turn_sharp_left',
    ROUNDABOUT_LEFT = 'roundabout_left',
    SCREEN_ROTATION_ALT = 'screen_rotation_alt',
    RAMP_LEFT = 'ramp_left',
    RAMP_RIGHT = 'ramp_right',
    EMERGENCY_RECORDING = 'emergency_recording',
    FIRE_TRUCK = 'fire_truck',
    FIRE_HYDRANT_ALT = 'fire_hydrant_alt',
    
    /* Audio & Video */
    PLAY_ARROW = 'play_arrow',
    PLAY_CIRCLE_FILLED = 'play_circle_filled',
    VIDEOCAM = 'videocam',
    PLAY_CIRCLE = 'play_circle',
    MIC = 'mic',
    VOLUME_UP = 'volume_up',
    PAUSE = 'pause',
    PLAY_CIRCLE_OUTLINE = 'play_circle_outline',
    VOLUME_OFF = 'volume_off',
    REPLAY = 'replay',
    SKIP_NEXT = 'skip_next',
    
    LIBRARY_BOOKS = 'library_books',
    SPEED = 'speed',
    STOP = 'stop',
    FIBER_MANUAL_RECORD = 'fiber_manual_record',
    MOVIE = 'movie',
    SKIP_PREVIOUS = 'skip_previous',
    PLAYLIST_ADD = 'playlist_add',
    NEW_RELEASES = 'new_releases',
    EQUALIZER = 'equalizer',
    LOOP = 'loop',
    FAST_FORWARD = 'fast_forward',
    
    WEB = 'web',
    VIDEO_LIBRARY = 'video_library',
    PLAYLIST_ADD_CHECK = 'playlist_add_check',
    MIC_OFF = 'mic_off',
    LIBRARY_ADD = 'library_add',
    VIDEO_CALL = 'video_call',
    PAUSE_CIRCLE = 'pause_circle',
    SUBSCRIPTIONS = 'subscriptions',
    REPEAT = 'repeat',
    STOP_CIRCLE = 'stop_circle',
    VOLUME_MUTE = 'volume_mute',
    
    SHUFFLE = 'shuffle',
    NOT_INTERESTED = 'not_interested',
    SORT_BY_ALPHA = 'sort_by_alpha',
    MIC_NONE = 'mic_none',
    LIBRARY_MUSIC = 'library_music',
    FAST_REWIND = 'fast_rewind',
    VIDEOCAM_OFF = 'videocam_off',
    VOLUME_DOWN = 'volume_down',
    QUEUE_MUSIC = 'queue_music',
    RECENT_ACTORS = 'recent_actors',
    WEB_ASSET = 'web_asset',
    
    PAUSE_CIRCLE_FILLED = 'pause_circle_filled',
    HEARING = 'hearing',
    LIBRARY_ADD_CHECK = 'library_add_check',
    SUBTITLES = 'subtitles',
    PAUSE_CIRCLE_OUTLINE = 'pause_circle_outline',
    ALBUM = 'album',
    FIBER_NEW = 'fiber_new',
    NOTE = 'note',
    AV_TIMER = 'av_timer',
    RADIO = 'radio',
    GAMES = 'games',
    
    PLAYLIST_PLAY = 'playlist_play',
    REPLAY_CIRCLE_FILLED = 'replay_circle_filled',
    BRANDING_WATERMARK = 'branding_watermark',
    QUEUE = 'queue',
    FORWARD_10 = 'forward_10',
    REPLAY_10 = 'replay_10',
    CLOSED_CAPTION = 'closed_caption',
    VIDEO_SETTINGS = 'video_settings',
    FEATURED_PLAY_LIST = 'featured_play_list',
    CONTROL_CAMERA = 'control_camera',
    PLAYLIST_ADD_CHECK_CIRCLE = 'playlist_add_check_circle',
    
    ADD_TO_QUEUE = 'add_to_queue',
    SLOW_MOTION_VIDEO = 'slow_motion_video',
    AIRPLAY = 'airplay',
    REPEAT_ONE = 'repeat_one',
    CALL_TO_ACTION = 'call_to_action',
    SNOOZE = 'snooze',
    HIGH_QUALITY = 'high_quality',
    HD = 'hd',
    REPEAT_ON = 'repeat_on',
    CLOSED_CAPTION_OFF = 'closed_caption_off',
    PLAYLIST_REMOVE = 'playlist_remove',
    
    REPLAY_30 = 'replay_30',
    FEATURED_VIDEO = 'featured_video',
    CINK_G = '5g',
    SHUFFLE_ON = 'shuffle_on',
    FORWARD_30 = 'forward_30',
    MUSIC_VIDEO = 'music_video',
    REPLAY_5 = 'replay_5',
    QUEUE_PLAY_NEXT = 'queue_play_next',
    PLAYLIST_ADD_CIRCLE = 'playlist_add_circle',
    ART_TRACK = 'art_track',
    HEARING_DISABLED = 'hearing_disabled',
    
    FORWARD_5 = 'forward_5',
    EXPLICIT = 'explicit',
    QUATRE_K = '4k',
    AUDIO_FILE = 'audio_file',
    FIBER_SMART_RECORD = 'fiber_smart_record',
    VIDEO_LABEL = 'video_label',
    INTERPRETER_MODE = 'interpreter_mode',
    VIDEO_FILE = 'video_file',
    REPEAT_ONE_ON = 'repeat_one_on',
    CLOSED_CAPTION_DISABLED = 'closed_caption_disabled',
    SURROUND_SOUND = 'surround_sound',
    
    REMOVE_FROM_QUEUE = 'remove_from_queue',
    PLAY_DISABLED = 'play_disabled',
    WEB_ASSET_OFF = 'web_asset_off',
    SD = 'sd',
    MISSED_VIDEO_CALL = 'missed_video_call',
    DIX_K = '10k',
    FIBER_PIN = 'fiber_pin',
    FIBER_DVR = 'fiber_dvr',
    QUATRE_K_PLUS = '4k_plus',
    UN_K = '1k',
    LYRICS = 'lyrics',
    HUIT_K = '8k',
    UN_K_PLUS = '1k_plus',
    HUIT_K_PLUS = '8k_plus',
    NEUF_K_PLUS = '9k_plus',
    CINQ_K = '5k',
    TROIS_K = '3k',
    CINQ_K_PLUS = '5k_plus',
    DEUX_K_PLUS = '2k_plus',
    SEPT_K = '7k',
    SIX_K_PLUS = '6k_plus',
    TROIS_K_PLUS = '3k_plus',
    SIX_K = '6k',
    SEPT_K_PLUS = '7k_plus',
    NEUF_K = '9k',
    

    /* File */
    FILE_DOWNLOAD = 'file_download',
    FILE_UPLOAD = 'file_upload',
    DOWNLOAD = 'download',
    FOLDER = 'folder',
    GRID_VIEW = 'grid_view',
    UPLOAD_FILE = 'upload_file',
    CLOUD_UPLOAD = 'cloud_upload',
    FOLDER_OPEN = 'folder_open',
    CLOUD = 'cloud',
    TEXT_SNIPPET = 'text_snippet',
    REQUEST_QUOTE = 'request_quote',
    
    CLOUD_DOWNLOAD = 'cloud_download',
    DRIVE_FILE_RENAME_OUTLINE = 'drive_file_rename_outline',
    UPLOAD = 'upload',
    ATTACHMENT = 'attachment',
    DOWNLOAD_FOR_OFFLINE = 'download_for_offline',
    CREATE_NEW_FOLDER = 'create_new_folder',
    DOWNLOADING = 'downloading',
    NEWSPAPER = 'newspaper',
    FOLDER_SHARED = 'folder_shared',
    CLOUD_DONE = 'cloud_done',
    TOPIC = 'topic',
    
    CLOUD_QUEUE = 'cloud_queue',
    DOWNLOAD_DONE = 'download_done',
    WORKSPACES = 'workspaces',
    APPROVAL = 'approval',
    CLOUD_OFF = 'cloud_off',
    DRIVE_FILE_MOVE = 'drive_file_move',
    DRIVE_FOLDER_UPLOAD = 'drive_folder_upload',
    FILE_DOWNLOAD_DONE = 'file_download_done',
    FILE_OPEN = 'file_open',
    ATTACH_EMAIL = 'attach_email',
    RULE_FOLDER = 'rule_folder',
    
    CLOUD_SYNC = 'cloud_sync',
    CLOUD_CIRCLE = 'cloud_circle',
    SNIPPET_FOLDER = 'snippet_folder',
    FOLDER_ZIP = 'folder_zip',
    FILE_DOWNLOAD_OFF = 'file_download_off',
    FOLDER_COPY = 'folder_copy',
    DIFFERENCE = 'difference',
    DRIVE_FILE_MOVE_RTL = 'drive_file_move_rtl',
    FOLDER_DELETE = 'folder_delete',
    FOLDER_OFF = 'folder_off',
    FORMAT_OVERLINE = 'format_overline',

    /* Toggle */
    STAR = 'star',
    CHECK_BOX = 'check_box',
    CHECK_BOX_OUTLINE_BLANK = 'check_box_outline_blank',
    RADIO_BUTTON_UNCHECKED = 'radio_button_unchecked',
    RADIO_BUTTON_CHECKED = 'radio_button_checked',
    STAR_BORDER = 'star_border',
    TOGGLE_ON = 'toggle_on',
    STAR_OUTLINE = 'star_outline',
    TOGGLE_OFF = 'toggle_off',
    STAR_HALF = 'star_half',
    INDETERMINATE_CHECK_BOX = 'indeterminate_check_box',
    STAR_PURPLE500 = 'star_purple500',
    STAR_BORDER_PURPLE500 = 'star_border_purple500',

    /* Alerte */
    WARNING = 'warning',
    ERROR = 'error',
    ERROR_OUTLINE = 'error_outline',
    WARNING_AMBER = 'warning_amber',
    NOTIFICATION_IMPORTANT = 'notification_important',
    ADD_ALERT = 'add_alert',
    AUTO_DELETE = 'auto_delete',
    
    /* Social */
    PERSON = 'person',
    NOTIFICATIONS = 'notifications',
    GROUPS = 'groups',
    PEOPLE = 'people',
    SHARE = 'share',
    PERSON_OUTLINE = 'person_outline',
    SCHOOL = 'school',
    PERSON_ADD = 'person_add',
    PUBLIC = 'public',
    EMOJI_EVENTS = 'emoji_events',
    GROUP = 'group',
    
    WHATSAPP = 'whatsapp',
    NOTIFICATIONS_ACTIVE = 'notifications_active',
    ENGINEERING = 'engineering',
    CONSTRUCTION = 'construction',
    PEOPLE_ALT = 'people_alt',
    GROUP_ADD = 'group_add',
    PSYCHOLOGY = 'psychology',
    HEALTH_AND_SAFETY = 'health_and_safety',
    TRAVEL_EXPLORE = 'travel_explore',
    EMOJI_EMOTIONS = 'emoji_emotions',
    WATER_DROP = 'water_drop',
    
    NOTIFICATIONS_NONE = 'notifications_none',
    THUMB_UP_ALT = 'thumb_up_alt',
    SPORTS_ESPORTS = 'sports_esports',
    SENTIMENT_SATISFIED = 'sentiment_satisfied',
    IOS_SHARE = 'ios_share',
    LOCATION_CITY = 'location_city',
    PERSON_ADD_ALT = 'person_add_alt',
    PRECISION_MANUFACTURING = 'precision_manufacturing',
    EMOJI_OBJECTS = 'emoji_objects',
    SENTIMENT_VERY_SATISFIED = 'sentiment_very_satisfied',
    MILITARY_TECH = 'military_tech',
    
    SCIENCE = 'science',
    HISTORY_EDU = 'history_edu',
    CAKE = 'cake',
    SENTIMENT_DISSATISFIED = 'sentiment_dissatisfied',
    CORONAVIRUS = 'coronavirus',
    SENTIMENT_VERY_DISSATISFIED = 'sentiment_very_dissatisfied',
    EMOJI_PEOPLE = 'emoji_people',
    SELF_IMPROVEMENT = 'self_improvement',
    WORKSPACE_PREMIUM = 'workspace_premium',
    PERSON_REMOVE = 'person_remove',
    POLL = 'poll',
    
    SPORTS_SOCCER = 'sports_soccer',
    FEMALE = 'female',
    DOMAIN = 'domain',
    WHATSHOT = 'whatshot',
    MOOD = 'mood',
    PEOPLE_OUTLINE = 'people_outline',
    RECOMMEND = 'recommend',
    MALE = 'male',
    HANDSHAKE = 'handshake',
    PERSON_OFF = 'person_off',
    RECYCLING = 'recycling',
    
    MASKS = 'masks',
    SENTIMENT_NEUTRAL = 'sentiment_neutral',
    CONNECT_WITHOUT_CONTACT = 'connect_without_contact',
    PERSON_ADD_ALT_1 = 'person_add_alt_1',
    BACK_HAND = 'back_hand',
    HIKING = 'hiking',
    ARCHITECTURE = 'architecture',
    NOTIFICATIONS_OFF = 'notifications_off',
    WAVING_HAND = 'waving_hand',
    LUGGAGE = 'luggage',
    THUMB_DOWN_ALT = 'thumb_down_alt',
    
    FRONT_HAND = 'front_hand',
    MOOD_BAD = 'mood_bad',
    EMOJI_NATURE = 'emoji_nature',
    SWITCH_ACCOUNT = 'switch_account',
    VACCINES = 'vaccines',
    CATCHING_POKEMON = 'catching_pokemon',
    REAL_ESTATE_AGENT = 'real_estate_agent',
    NIGHTS_STAY = 'nights_stay',
    KING_BED = 'king_bed',
    SPORTS_BASKETBALL = 'sports_basketball',
    INTERESTS = 'interests',
    
    NOTIFICATION_ADD = 'notification_add',
    EMOJI_SYMBOLS = 'emoji_symbols',
    SPORTS = 'sports',
    SPORTS_KABADDI = 'sports_kabaddi',
    EMOJI_FOOD_BEVERAGE = 'emoji_food_beverage',
    SICK = 'sick',
    REDUCE_CAPACITY = 'reduce_capacity',
    EMOJI_TRANSPORTATION = 'emoji_transportation',
    SPORTS_TENNIS = 'sports_tennis',
    TRANSGENDER = 'transgender',
    COMPOST = 'compost',
    
    COOKIE = 'cookie',
    OUTDOOR_GRILL = 'outdoor_grill',
    SOCIAL_DISTANCE = 'social_distance',
    ELDERLY = 'elderly',
    DECK = 'deck',
    MAN = 'man',
    ADD_MODERATOR = 'add_moderator',
    CRUELTY_FREE = 'cruelty_free',
    FOLLOW_THE_SIGNS = 'follow_the_signs',
    CLEAN_HANDS = 'clean_hands',
    HEART_BROKEN = 'heart_broken',
    
    PLUS_ONE = 'plus_one',
    PIANO = 'piano',
    FIREPLACE = 'fireplace',
    SANITIZER = 'sanitizer',
    WOMAN = 'woman',
    SURFING = 'surfing',
    SPORTS_MOTORSPORTS = 'sports_motorsports',
    ADD_REACTION = 'add_reaction',
    SPORTS_HANDBALL = 'sports_handball',
    PERSONAL_INJURY = 'personal_injury',
    SPORTS_BASEBALL = 'sports_baseball',
    
    EDIT_NOTIFICATIONS = 'edit_notifications',
    PIX = 'pix',
    SPORTS_VOLLEYBALL = 'sports_volleyball',
    PAGES = 'pages',
    SPORTS_FOOTBALL = 'sports_football',
    DOWNHILL_SKIING = 'downhill_skiing',
    KAYAKING = 'kayaking',
    SCALE = 'scale',
    HIVE = 'hive',
    SKATEBOARDING = 'skateboarding',
    PUBLIC_OFF = 'public_off',
    
    SINGLE_BED = 'single_bed',
    REMOVE_MODERATOR = 'remove_moderator',
    NOTIFICATIONS_PAUSED = 'notifications_paused',
    SAFETY_DIVIDER = 'safety_divider',
    PERSON_REMOVE_ALT_1 = 'person_remove_alt_1',
    GROUP_REMOVE = 'group_remove',
    CO2 = 'co2',
    SPORTS_CRICKET = 'sports_cricket',
    NORDIC_WALKING = 'nordic_walking',
    SPORTS_MMA = 'sports_mma',
    BOY = 'boy',
    
    GROUP_OFF = 'group_off',
    SPORTS_GOLF = 'sports_golf',
    SIX_FT_APART = '6_ft_apart',
    FITBIT = 'fitbit',
    PARAGLIDING = 'paragliding',
    SNOWBOARDING = 'snowboarding',
    PARTY_MODE = 'party_mode',
    KITESURFING = 'kitesurfing',
    WALLET = 'wallet',
    GIRL = 'girl',
    SPORTS_MARTIAL_ARTS = 'sports_martial_arts',
    
    DOMAIN_ADD = 'domain_add',
    SNOWSHOEING = 'snowshoeing',
    SPORTS_HOCKEY = 'sports_hockey',
    ICE_SKATING = 'ice_skating',
    SPORTS_RUGBY = 'sports_rugby',
    SLEDDING = 'sledding',
    SOUTH_AMERICA = 'south_america',
    SPORTS_GYMNASTICS = 'sports_gymnastics',
    ELDERLY_WOMAN = 'elderly_woman',
    THUNDERSTORM = 'thunderstorm',
    NO_LUGGAGE = 'no_luggage',
    
    SCOREBOARD = 'scoreboard',
    DIVERSITY_3 = 'diversity_3',
    PIANO_OFF = 'piano_off',
    DIVERSITY_1 = 'diversity_1',
    SIGN_LANGUAGE = 'sign_language',
    SCUBA_DIVING = 'scuba_diving',
    CYCLONE = 'cyclone',
    GROUPS_2 = 'groups_2',
    FLOOD = 'flood',
    DIVERSITY_2 = 'diversity_2',
    PSYCHOLOGY_ALT = 'psychology_alt',
    
    ROLLER_SKATING = 'roller_skating',
    TSUNAMI = 'tsunami',
    LANDSLIDE = 'landslide',
    TORNADO = 'tornado',
    SEVERE_COLD = 'severe_cold',
    VOLCANO = 'volcano',
    GROUPS_3 = 'groups_3',
    FACE_6 = 'face_6',
    FACE_3 = 'face_3',
    PERSON_2 = 'person_2',
    DIXHUIT_UP_RATING = '18_up_rating',
    
    FACE_4 = 'face_4',
    FACE_2 = 'face_2',
    NO_ADULT_CONTENT = 'no_adult_content',
    PERSON_3 = 'person_3',
    PERSON_4 = 'person_4',
    FACE_5 = 'face_5',
    WOMAN_2 = 'woman_2',
    ASSIST_WALKER = 'assist_walker',
    BLIND = 'blind',
    MAN_2 = 'man_2',
    MAN_3 = 'man_3',
    MAN_4 = 'man_4',
    
    
    /* Content */
    ADD = 'add',
    ADD_CIRCLE_OUTLINE = 'add_circle_outline',
    CONTENT_COPY = 'content_copy',
    ADD_CIRCLE = 'add_circle',
    SEND = 'send',
    CLEAR = 'clear',
    MAIL = 'mail',
    SAVE = 'save',
    LINK = 'link',
    REMOVE = 'remove',
    FILTER_LIST = 'filter_list',
    
    INVENTORY_2 = 'inventory_2',
    INSIGHTS = 'insights',
    INVENTORY = 'inventory',
    REMOVE_CIRCLE_OUTLINE = 'remove_circle_outline',
    SORT = 'sort',
    BOLT = 'bolt',
    FLAG = 'flag',
    REPLY = 'reply',
    ADD_BOX = 'add_box',
    REMOVE_CIRCLE = 'remove_circle',
    PUSH_PIN = 'push_pin',
    
    CREATE = 'create',
    BLOCK = 'block',
    CALCULATE = 'calculate',
    UNDO = 'undo',
    HOW_TO_REG = 'how_to_reg',
    CONTENT_PASTE = 'content_paste',
    REPORT = 'report',
    FILE_COPY = 'file_copy',
    BACKSPACE = 'backspace',
    SHIELD = 'shield',
    ARCHIVE = 'archive',
    
    SAVE_ALT = 'save_alt',
    POLICY = 'policy',
    TAG = 'tag',
    CHANGE_CIRCLE = 'change_circle',
    REDO = 'redo',
    CONTENT_CUT = 'content_cut',
    FORWARD = 'forward',
    INBOX = 'inbox',
    OUTLINED_FLAG = 'outlined_flag',
    DRAFTS = 'drafts',
    LINK_OFF = 'link_off',
    
    BALLOT = 'ballot',
    BIOTECH = 'biotech',
    REPORT_GMAILERRORRED = 'report_gmailerrorred',
    MARKUNREAD = 'markunread',
    STACKED_BAR_CHART = 'stacked_bar_chart',
    DELETE_SWEEP = 'delete_sweep',
    SQUARE_FOOT = 'square_foot',
    STREAM = 'stream',
    ADD_LINK = 'add_link',
    WHERE_TO_VOTE = 'where_to_vote',
    COPY_ALL = 'copy_all',
    
    MOVE_TO_INBOX = 'move_to_inbox',
    DYNAMIC_FEED = 'dynamic_feed',
    WAVES = 'waves',
    UNARCHIVE = 'unarchive',
    REPLY_ALL = 'reply_all',
    SELECT_ALL = 'select_all',
    LOW_PRIORITY = 'low_priority',
    TEXT_FORMAT = 'text_format',
    CONTENT_PASTE_SEARCH = 'content_paste_search',
    WEEKEND = 'weekend',
    FONT_DOWNLOAD = 'font_download',
    
    HOW_TO_VOTE = 'how_to_vote',
    UPCOMING = 'upcoming',
    GESTURE = 'gesture',
    ATTRIBUTION = 'attribution',
    SAVE_AS = 'save_as',
    NEXT_WEEK = 'next_week',
    CONTENT_PASTE_GO = 'content_paste_go',
    FLAG_CIRCLE = 'flag_circle',
    CONTENT_PASTE_OFF = 'content_paste_off',
    FILTER_LIST_OFF = 'filter_list_off',
    REPORT_OFF = 'report_off',
    
    FONT_DOWNLOAD_OFF = 'font_download_off',
    DESELECT = 'deselect',
    WEB_STORIES = 'web_stories',
    
    /* Editor */
    ATTACH_MONEY = 'attach_money',
    FORMAT_LIST_BULLETED = 'format_list_bulleted',
    MODE_EDIT = 'mode_edit',
    EDIT_NOTE = 'edit_note',
    MONETIZATION_ON = 'monetization_on',
    ATTACH_FILE = 'attach_file',
    POST_ADD = 'post_add',
    BAR_CHART = 'bar_chart',
    CHECKLIST = 'checklist',
    DRAG_HANDLE = 'drag_handle',
    INSERT_DRIVE_FILE = 'insert_drive_file',
    
    SHOW_CHART = 'show_chart',
    FORMAT_QUOTE = 'format_quote',
    FORMAT_LIST_NUMBERED = 'format_list_numbered',
    BORDER_COLOR = 'border_color',
    TABLE_CHART = 'table_chart',
    PIE_CHART = 'pie_chart',
    QUERY_STATS = 'query_stats',
    NOTES = 'notes',
    FORMAT_BOLD = 'format_bold',
    INSERT_PHOTO = 'insert_photo',
    TEXT_FIELDS = 'text_fields',
    
    INSERT_EMOTICON = 'insert_emoticon',
    TITLE = 'title',
    TABLE_ROWS = 'table_rows',
    AUTO_GRAPH = 'auto_graph',
    PUBLISH = 'publish',
    MODE = 'mode',
    INSERT_CHART_OUTLINED = 'insert_chart_outlined',
    CHECKLIST_RTL = 'checklist_rtl',
    MODE_COMMENT = 'mode_comment',
    DRAW = 'draw',
    INSERT_INVITATION = 'insert_invitation',
    
    INSERT_LINK = 'insert_link',
    FUNCTIONS = 'functions',
    MODE_EDIT_OUTLINE = 'mode_edit_outline',
    FORMAT_ITALIC = 'format_italic',
    FORMAT_ALIGN_LEFT = 'format_align_left',
    HORIZONTAL_RULE = 'horizontal_rule',
    FORMAT_COLOR_FILL = 'format_color_fill',
    ADD_COMMENT = 'add_comment',
    INSERT_CHART = 'insert_chart',
    LINEAR_SCALE = 'linear_scale',
    FORMAT_SIZE = 'format_size',
    
    STACKED_LINE_CHART = 'stacked_line_chart',
    FORMAT_UNDERLINED = 'format_underlined',
    BUBBLE_CHART = 'bubble_chart',
    INSERT_COMMENT = 'insert_comment',
    MONEY_OFF = 'money_off',
    VERTICAL_ALIGN_BOTTOM = 'vertical_align_bottom',
    HEIGHT = 'height',
    VERTICAL_ALIGN_TOP = 'vertical_align_top',
    FORMAT_ALIGN_CENTER = 'format_align_center',
    FORMAT_PAINT = 'format_paint',
    SCHEMA = 'schema',
    
    AREA_CHART = 'area_chart',
    FORMAT_COLOR_TEXT = 'format_color_text',
    FORMAT_ALIGN_RIGHT = 'format_align_right',
    SCATTER_PLOT = 'scatter_plot',
    FORMAT_LIST_NUMBERED_RTL = 'format_list_numbered_rtl',
    HIGHLIGHT = 'highlight',
    FORMAT_ALIGN_JUSTIFY = 'format_align_justify',
    MERGE_TYPE = 'merge_type',
    SQUARE = 'square',
    ADD_CHART = 'add_chart',
    FORMAT_SHAPES = 'format_shapes',
    
    MONEY_OFF_CSRED = 'money_off_csred',
    NUMBERS = 'numbers',
    PIE_CHART_OUTLINE = 'pie_chart_outline',
    SHORT_TEXT = 'short_text',
    FORMAT_INDENT_INCREASE = 'format_indent_increase',
    ALIGN_HORIZONTAL_LEFT = 'align_horizontal_left',
    STRIKETHROUGH_S = 'strikethrough_s',
    DATA_OBJECT = 'data_object',
    VERTICAL_ALIGN_CENTER = 'vertical_align_center',
    FORMAT_COLOR_RESET = 'format_color_reset',
    MULTILINE_CHART = 'multiline_chart',
    
    SCORE = 'score',
    BORDER_ALL = 'border_all',
    HEXAGON = 'hexagon',
    SPACE_BAR = 'space_bar',
    FORMAT_INDENT_DECREASE = 'format_indent_decrease',
    RECTANGLE = 'rectangle',
    FORMAT_CLEAR = 'format_clear',
    MOVE_UP = 'move_up',
    FORMAT_LINE_SPACING = 'format_line_spacing',
    ALIGN_VERTICAL_BOTTOM = 'align_vertical_bottom',
    HORIZONTAL_DISTRIBUTE = 'horizontal_distribute',
    
    ALIGN_HORIZONTAL_CENTER = 'align_horizontal_center',
    MOVE_DOWN = 'move_down',
    FORMAT_STRIKETHROUGH = 'format_strikethrough',
    ALIGN_HORIZONTAL_RIGHT = 'align_horizontal_right',
    VERTICAL_DISTRIBUTE = 'vertical_distribute',
    SUPERSCRIPT = 'superscript',
    CANDLESTICK_CHART = 'candlestick_chart',
    MARGIN = 'margin',
    TEXT_INCREASE = 'text_increase',
    WRAP_TEXT = 'wrap_text',
    ALIGN_VERTICAL_TOP = 'align_vertical_top',
    
    BORDER_CLEAR = 'border_clear',
    SUBSCRIPT = 'subscript',
    ALIGN_VERTICAL_CENTER = 'align_vertical_center',
    POLYLINE = 'polyline',
    DATA_ARRAY = 'data_array',
    BORDER_STYLE = 'border_style',
    PADDING = 'padding',
    PENTAGON = 'pentagon',
    BORDER_OUTER = 'border_outer',
    TEXT_DECREASE = 'text_decrease',
    LINE_AXIS = 'line_axis',
    
    INSERT_PAGE_BREAK = 'insert_page_break',
    BORDER_INNER = 'border_inner',
    BORDER_LEFT = 'border_left',
    BORDER_BOTTOM = 'border_bottom',
    FORMAT_TEXTDIRECTION_L_TO_R = 'format_textdirection_l_to_r',
    BORDER_VERTICAL = 'border_vertical',
    BORDER_HORIZONTAL = 'border_horizontal',
    FORMAT_TEXTDIRECTION_R_TO_L = 'format_textdirection_r_to_l',
    BORDER_TOP = 'border_top',
    BORDER_RIGHT = 'border_right',
    SHAPE_LINE = 'shape_line',
    TYPE_SPECIMEN = 'type_specimen',
    

    /* Image */
    EDIT = 'edit',
    NAVIGATE_NEXT = 'navigate_next',
    PHOTO_CAMERA = 'photo_camera',
    IMAGE = 'image',
    TUNE = 'tune',
    PICTURE_AS_PDF = 'picture_as_pdf',
    RECEIPT_LONG = 'receipt_long',
    CIRCLE = 'circle',
    TIMER = 'timer',
    AUTO_STORIES = 'auto_stories',
    COLLECTIONS = 'collections',
    
    NAVIGATE_BEFORE = 'navigate_before',
    ADD_A_PHOTO = 'add_a_photo',
    AUTO_AWESOME = 'auto_awesome',
    PALETTE = 'palette',
    REMOVE_RED_EYE = 'remove_red_eye',
    MUSIC_NOTE = 'music_note',
    WB_SUNNY = 'wb_sunny',
    ADD_PHOTO_ALTERNATE = 'add_photo_alternate',
    BRUSH = 'brush',
    FLASH_ON = 'flash_on',
    EURO = 'euro',
    
    CONTROL_POINT = 'control_point',
    AUTO_FIX_HIGH = 'auto_fix_high',
    LOOKS_ONE = 'looks_one',
    ADJUST = 'adjust',
    STYLE = 'style',
    STRAIGHTEN = 'straighten',
    CAMERA = 'camera',
    PHOTO_LIBRARY = 'photo_library',
    PORTRAIT = 'portrait',
    CAMERA_ALT = 'camera_alt',
    AUDIOTRACK = 'audiotrack',
    
    VIDEO_CAMERA_FRONT = 'video_camera_front',
    ROTATE_RIGHT = 'rotate_right',
    GRID_ON = 'grid_on',
    COLOR_LENS = 'color_lens',
    CROP_FREE = 'crop_free',
    TIMELAPSE = 'timelapse',
    LANDSCAPE = 'landscape',
    SLIDESHOW = 'slideshow',
    COLLECTIONS_BOOKMARK = 'collections_bookmark',
    CROP_SQUARE = 'crop_square',
    LOOKS_TWO = 'looks_two',
    
    LENS = 'lens',
    PANORAMA_FISH_EYE = 'panorama_fish_eye',
    CURRENCY_RUPEE = 'currency_rupee',
    FILTER_VINTAGE = 'filter_vintage',
    FILTER_DRAMA = 'filter_drama',
    COMPARE = 'compare',
    HEALING = 'healing',
    AUTO_AWESOME_MOTION = 'auto_awesome_motion',
    IMAGE_SEARCH = 'image_search',
    ROTATE_LEFT = 'rotate_left',
    
    CROP = 'crop',
    BLUR_ON = 'blur_on',
    WB_INCANDESCENT = 'wb_incandescent',
    CENTER_FOCUS_STRONG = 'center_focus_strong',
    FLARE = 'flare',
    WB_CLOUDY = 'wb_cloudy',
    FACE_RETOUCHING_NATURAL = 'face_retouching_natural',
    BRIGHTNESS_4 = 'brightness_4',
    FILTER_NONE = 'filter_none',
    COLORIZE = 'colorize',
    CASES = 'cases',
    
    ASSISTANT = 'assistant',
    BROKEN_IMAGE = 'broken_image',
    FILTER_CENTER_FOCUS = 'filter_center_focus',
    DEHAZE = 'dehaze',
    AUTO_AWESOME_MOSAIC = 'auto_awesome_mosaic',
    NATURE_PEOPLE = 'nature_people',
    PHOTO = 'photo',
    CROP_ORIGINAL = 'crop_original',
    FLASH_OFF = 'flash_off',
    BRIGHTNESS_6 = 'brightness_6',
    BRIGHTNESS_5 = 'brightness_5',
    
    TAG_FACES = 'tag_faces',
    DETAILS = 'details',
    FLIP_CAMERA_ANDROID = 'flip_camera_android',
    GRAIN = 'grain',
    FLIP = 'flip',
    LOUPE = 'loupe',
    BRIGHTNESS_1 = 'brightness_1',
    AUTO_FIX_NORMAL = 'auto_fix_normal',
    FLIP_CAMERA_IOS = 'flip_camera_ios',
    MOVIE_CREATION = 'movie_creation',
    IMAGE_NOT_SUPPORTED = 'image_not_supported',
    
    FILTER_1 = 'filter_1',
    PANORAMA = 'panorama',
    ADD_TO_PHOTOS = 'add_to_photos',
    CENTER_FOCUS_WEAK = 'center_focus_weak',
    ANIMATION = 'animation',
    MOVIE_FILTER = 'movie_filter',
    LOOKS_4 = 'looks_4',
    VIEW_COMFY = 'view_comfy',
    CROP_DIN = 'crop_din',
    FILTER = 'filter',
    BEDTIME = 'bedtime',
    
    CONTROL_POINT_DUPLICATE = 'control_point_duplicate',
    LEAK_ADD = 'leak_add',
    BRIGHTNESS_7 = 'brightness_7',
    NATURE = 'nature',
    TEXTURE = 'texture',
    PHOTO_SIZE_SELECT_ACTUAL = 'photo_size_select_actual',
    VIDEO_CAMERA_BACK = 'video_camera_back',
    TIMER_OFF = 'timer_off',
    INCOMPLETE_CIRCLE = 'incomplete_circle',
    TRANSFORM = 'transform',
    MOTION_PHOTOS_ON = 'motion_photos_on',
    
    VIEW_COMPACT = 'view_compact',
    PHOTO_CAMERA_FRONT = 'photo_camera_front',
    ROTATE_90_DEGREES_CCW = 'rotate_90_degrees_ccw',
    MIC_EXTERNAL_ON = 'mic_external_on',
    GRADIENT = 'gradient',
    LOOKS_5 = 'looks_5',
    ASSISTANT_PHOTO = 'assistant_photo',
    MUSIC_OFF = 'music_off',
    CURRENCY_BITCOIN = 'currency_bitcoin',
    THERMOSTAT_AUTO = 'thermostat_auto',
    EXPOSURE_PLUS_1 = 'exposure_plus_1',
    
    PHOTO_ALBUM = 'photo_album',
    HIDE_IMAGE = 'hide_image',
    SHUTTER_SPEED = 'shutter_speed',
    EXPOSURE = 'exposure',
    FILTER_2 = 'filter_2',
    FILTER_TILT_SHIFT = 'filter_tilt_shift',
    HDR_STRONG = 'hdr_strong',
    CROP_16_9 = 'crop_16_9',
    VRPANO = 'vrpano',
    LOOKS = 'looks',
    CONTRAST = 'contrast',
    
    WB_TWILIGHT = 'wb_twilight',
    LINKED_CAMERA = 'linked_camera',
    BLUR_CIRCULAR = 'blur_circular',
    FLASH_AUTO = 'flash_auto',
    CURRENCY_POUND = 'currency_pound',
    LOOKS_6 = 'looks_6',
    BRIGHTNESS_3 = 'brightness_3',
    MOTION_PHOTOS_AUTO = 'motion_photos_auto',
    CURRENCY_YEN = 'currency_yen',
    CROP_PORTRAIT = 'crop_portrait',
    TONALITY = 'tonality',

    BRIGHTNESS_2 = 'brightness_2',
    ISO = 'iso',
    PHOTO_SIZE_SELECT_SMALL = 'photo_size_select_small',
    PHOTO_FILTER = 'photo_filter',
    CROP_7_5 = 'crop_7_5',
    CROP_ROTATE = 'crop_rotate',
    FILTER_HDR = 'filter_hdr',
    HDR_WEAK = 'hdr_weak',
    PHOTO_SIZE_SELECT_LARGE = 'photo_size_select_large',
    FILTER_3 = 'filter_3',
    CAMERA_FRONT = 'camera_front',
    
    ROTATE_90_DEGREES_CW = 'rotate_90_degrees_cw',
    EXPOSURE_ZERO = 'exposure_zero',
    CROP_5_4 = 'crop_5_4',
    FILTER_FRAMES = 'filter_frames',
    CAMERA_ROLL = 'camera_roll',
    BURST_MODE = 'burst_mode',
    BLUR_LINEAR = 'blur_linear',
    FILTER_B_AND_W = 'filter_b_and_w',
    CROP_3_2 = 'crop_3_2',
    LOGO_DEV = 'logo_dev',
    CROP_LANDSCAPE = 'crop_landscape',
    
    SWITCH_CAMERA = 'switch_camera',
    SWITCH_VIDEO = 'switch_video',
    CURRENCY_RUBLE = 'currency_ruble',
    FILTER_7 = 'filter_7',
    EXPOSURE_PLUS_2 = 'exposure_plus_2',
    FILTER_4 = 'filter_4',
    FILTER_9_PLUS = 'filter_9_plus',
    WB_IRIDESCENT = 'wb_iridescent',
    MONOCHROME_PHOTOS = 'monochrome_photos',
    MOTION_PHOTOS_PAUSED = 'motion_photos_paused',
    GRID_OFF = 'grid_off',
    
    PHOTO_CAMERA_BACK = 'photo_camera_back',
    FILTER_5 = 'filter_5',
    FACE_RETOUCHING_OFF = 'face_retouching_off',
    AUTO_FIX_OFF = 'auto_fix_off',
    EXPOSURE_NEG_1 = 'exposure_neg_1',
    PANORAMA_PHOTOSPHERE = 'panorama_photosphere',
    LEAK_REMOVE = 'leak_remove',
    FILTER_9 = 'filter_9',
    TIMER_10 = 'timer_10',
    FILTER_8 = 'filter_8',
    VIDEO_STABLE = 'video_stable',
    
    WB_SHADE = 'wb_shade',
    MOTION_PHOTOS_OFF = 'motion_photos_off',
    FILTER_6 = 'filter_6',
    BLUR_OFF = 'blur_off',
    RAW_ON = 'raw_on',
    HDR_ON = 'hdr_on',
    PANORAMA_HORIZONTAL = 'panorama_horizontal',
    DIRTY_LENS = 'dirty_lens',
    VIGNETTE = 'vignette',
    IMAGE_ASPECT_RATIO = 'image_aspect_ratio',
    MOTION_PHOTOS_PAUSE = 'motion_photos_pause',
    
    TRENTE_FPS_SELECT = '30fps_select',
    CAMERA_REAR = 'camera_rear',
    TIMER_3 = 'timer_3',
    SOIXANTE_FPS_SELECT = '60fps_select',
    VINGT_QUATRE_MP = '24mp',
    PANORAMA_WIDE_ANGLE_SELECT = 'panorama_wide_angle_select',
    EXPOSURE_NEG_2 = 'exposure_neg_2',
    AUTOFPS_SELECT = 'autofps_select',
    PANORAMA_HORIZONTAL_SELECT = 'panorama_horizontal_select',
    DEBLUR = 'deblur',
    PANORAMA_WIDE_ANGLE = 'panorama_wide_angle',
    
    PANORAMA_PHOTOSPHERE_SELECT = 'panorama_photosphere_select',
    WB_AUTO = 'wb_auto',
    MIC_EXTERNAL_OFF = 'mic_external_off',
    HDR_PLUS = 'hdr_plus',
    PANORAMA_VERTICAL_SELECT = 'panorama_vertical_select',
    PANORAMA_VERTICAL = 'panorama_vertical',
    DOUZE_MP = '12mp',
    HDR_ENHANCED_SELECT = 'hdr_enhanced_select',
    HEVC = 'hevc',
    MP = 'mp',
    CURRENCY_YUAN = 'currency_yuan',
    CURRENCY_LIRA = 'currency_lira',
    DIX_HUIT_MP = '18mp',
    VINGT_TROIS_MP = '23mp',
    RAW_OFF = 'raw_off',
    HDR_OFF = 'hdr_off',
    DIX_MP = '10mp',
    ONZE_MP = '11mp',
    VINGT_MP = '20mp',
    TROIS_MP = '3mp',
    SEIZE_MP = '16mp',
    CURRENCY_FRANC = 'currency_franc',
    QUINZE_MP = '15mp',
    DIX_SEPT_MP = '17mp',
    TREIZE_MP = '13mp',
    VINGT_DEUX_MP = '22mp',
    DEUX_MP = '2mp',
    VINGT_UN_MP = '21mp',
    CINQ_MP = '5mp',
    DIX_NEUF_MP = '19mp',
    QUATRE_MP = '4mp',
    SEPT_MP = '7mp',
    HUIT_MP = '8mp',
    NEUF_MP = '9mp',
    SIX_MP = '6mp',
    QUATORZE_MP = '14mp',
    BEDTIME_OFF = 'bedtime_off',
    
    /* Communication */
    EMAIL = 'email',
    LOCATION_ON = 'location_on',
    CALL = 'call',
    PHONE = 'phone',
    BUSINESS = 'business',
    CHAT = 'chat',
    MAIL_OUTLINE = 'mail_outline',
    LIST_ALT = 'list_alt',
    VPN_KEY = 'vpn_key',
    QR_CODE_SCANNER = 'qr_code_scanner',
    CHAT_BUBBLE_OUTLINE = 'chat_bubble_outline',
    
    ALTERNATE_EMAIL = 'alternate_email',
    FORUM = 'forum',
    CHAT_BUBBLE = 'chat_bubble',
    TEXTSMS = 'textsms',
    CONTACT_MAIL = 'contact_mail',
    PERSON_SEARCH = 'person_search',
    QR_CODE_2 = 'qr_code_2',
    QR_CODE = 'qr_code',
    SENTIMENT_SATISFIED_ALT = 'sentiment_satisfied_alt',
    MESSAGE = 'message',
    COMMENT = 'comment',
    
    CONTACTS = 'contacts',
    APP_REGISTRATION = 'app_registration',
    IMPORT_CONTACTS = 'import_contacts',
    CONTACT_PHONE = 'contact_phone',
    LIVE_HELP = 'live_help',
    IMPORT_EXPORT = 'import_export',
    KEY = 'key',
    FORWARD_TO_INBOX = 'forward_to_inbox',
    RSS_FEED = 'rss_feed',
    HOURGLASS_BOTTOM = 'hourglass_bottom',
    HOURGLASS_TOP = 'hourglass_top',
    
    MARK_EMAIL_READ = 'mark_email_read',
    READ_MORE = 'read_more',
    MARK_EMAIL_UNREAD = 'mark_email_unread',
    CALL_END = 'call_end',
    MORE_TIME = 'more_time',
    DOCUMENT_SCANNER = 'document_scanner',
    CLEAR_ALL = 'clear_all',
    HUB = 'hub',
    DIALPAD = 'dialpad',
    PHONE_ENABLED = 'phone_enabled',
    MARK_CHAT_UNREAD = 'mark_chat_unread',
    
    TROIS_P = '3p',
    CANCEL_PRESENTATION = 'cancel_presentation',
    SCREEN_SHARE = 'screen_share',
    CALL_MADE = 'call_made',
    CALL_SPLIT = 'call_split',
    UNSUBSCRIBE = 'unsubscribe',
    PRESENT_TO_ALL = 'present_to_all',
    DOMAIN_VERIFICATION = 'domain_verification',
    ADD_IC_CALL = 'add_ic_call',
    MARK_CHAT_READ = 'mark_chat_read',
    PHONELINK_RING = 'phonelink_ring',
    
    STAY_CURRENT_PORTRAIT = 'stay_current_portrait',
    CALL_RECEIVED = 'call_received',
    PHONELINK_LOCK = 'phonelink_lock',
    PHONE_DISABLED = 'phone_disabled',
    DUO = 'duo',
    RING_VOLUME = 'ring_volume',
    PHONELINK_SETUP = 'phonelink_setup',
    LOCATION_OFF = 'location_off',
    STAY_PRIMARY_PORTRAIT = 'stay_primary_portrait',
    CO_PRESENT = 'co_present',
    SWAP_CALLS = 'swap_calls',
    
    VOICEMAIL = 'voicemail',
    CALL_MERGE = 'call_merge',
    MOBILE_SCREEN_SHARE = 'mobile_screen_share',
    PHONELINK_ERASE = 'phonelink_erase',
    CELL_TOWER = 'cell_tower',
    PERSON_ADD_DISABLED = 'person_add_disabled',
    DOMAIN_DISABLED = 'domain_disabled',
    CALL_MISSED_OUTGOING = 'call_missed_outgoing',
    CELL_WIFI = 'cell_wifi',
    SPEAKER_PHONE = 'speaker_phone',
    DESKTOP_ACCESS_DISABLED = 'desktop_access_disabled',
    
    STOP_SCREEN_SHARE = 'stop_screen_share',
    SPOKE = 'spoke',
    CALL_MISSED = 'call_missed',
    PRINT_DISABLED = 'print_disabled',
    PAUSE_PRESENTATION = 'pause_presentation',
    DIALER_SIP = 'dialer_sip',
    INVERT_COLORS_OFF = 'invert_colors_off',
    RTT = 'rtt',
    WIFI_CALLING = 'wifi_calling',
    PORTABLE_WIFI_OFF = 'portable_wifi_off',
    COMMENTS_DISABLED = 'comments_disabled',
    
    STAY_CURRENT_LANDSCAPE = 'stay_current_landscape',
    SIP = 'sip',
    NAT = 'nat',
    MARK_UNREAD_CHAT_ALT = 'mark_unread_chat_alt',
    STAY_PRIMARY_LANDSCAPE = 'stay_primary_landscape',
    NO_SIM = 'no_sim',
    SEND_TIME_EXTENSION = 'send_time_extension',
    KEY_OFF = 'key_off',
    MAIL_LOCK = 'mail_lock',
    VPN_KEY_OFF = 'vpn_key_off',
    CONTACT_EMERGENCY = 'contact_emergency',
    

    /* Notification */
    SUPPORT_AGENT = 'support_agent',
    WIFI = 'wifi',
    ACCOUNT_TREE = 'account_tree',
    SYNC = 'sync',
    EVENT_AVAILABLE = 'event_available',
    PRIORITY_HIGH = 'priority_high',
    PHONE_IN_TALK = 'phone_in_talk',
    EVENT_NOTE = 'event_note',
    CONFIRMATION_NUMBER = 'confirmation_number',
    SMS = 'sms',
    LIVE_TV = 'live_tv',
    
    ONDEMAND_VIDEO = 'ondemand_video',
    WIFI_OFF = 'wifi_off',
    DRIVE_ETA = 'drive_eta',
    EVENT_BUSY = 'event_busy',
    DO_NOT_DISTURB_ON = 'do_not_disturb_on',
    WC = 'wc',
    MORE = 'more',
    POWER_SETTINGS_NEW = 'power_settings_new',
    DO_NOT_DISTURB = 'do_not_disturb',
    SYNC_PROBLEM = 'sync_problem',
    TIME_TO_LEAVE = 'time_to_leave',
    
    VPN_LOCK = 'vpn_lock',
    DO_DISTURB_ON = 'do_disturb_on',
    ENHANCED_ENCRYPTION = 'enhanced_encryption',
    RUNNING_WITH_ERRORS = 'running_with_errors',
    FOLDER_SPECIAL = 'folder_special',
    NETWORK_CHECK = 'network_check',
    DO_DISTURB = 'do_disturb',
    SMS_FAILED = 'sms_failed',
    PHONE_CALLBACK = 'phone_callback',
    SYSTEM_UPDATE = 'system_update',
    ADB = 'adb',
    
    POWER_OFF = 'power_off',
    PERSONAL_VIDEO = 'personal_video',
    PHONE_FORWARDED = 'phone_forwarded',
    VOICE_CHAT = 'voice_chat',
    VIBRATION = 'vibration',
    AIRLINE_SEAT_RECLINE_NORMAL = 'airline_seat_recline_normal',
    DO_DISTURB_ALT = 'do_disturb_alt',
    DO_NOT_DISTURB_ALT = 'do_not_disturb_alt',
    SYNC_DISABLED = 'sync_disabled',
    TAP_AND_PLAY = 'tap_and_play',
    NO_ENCRYPTION = 'no_encryption',
    
    SD_CARD = 'sd_card',
    PHONE_MISSED = 'phone_missed',
    AIRLINE_SEAT_RECLINE_EXTRA = 'airline_seat_recline_extra',
    IMAGESEARCH_ROLLER = 'imagesearch_roller',
    MMS = 'mms',
    DISC_FULL = 'disc_full',
    BLUETOOTH_AUDIO = 'bluetooth_audio',
    NO_ENCRYPTION_GMAILERRORRED = 'no_encryption_gmailerrorred',
    SD_CARD_ALERT = 'sd_card_alert',
    SIM_CARD_ALERT = 'sim_card_alert',
    DO_NOT_DISTURB_OFF = 'do_not_disturb_off',
    
    AIRLINE_SEAT_INDIVIDUAL_SUITE = 'airline_seat_individual_suite',
    PHONE_PAUSED = 'phone_paused',
    PHONE_LOCKED = 'phone_locked',
    DO_DISTURB_OFF = 'do_disturb_off',
    AIRLINE_SEAT_FLAT = 'airline_seat_flat',
    NETWORK_LOCKED = 'network_locked',
    SYNC_LOCK = 'sync_lock',
    TV_OFF = 'tv_off',
    AIRLINE_SEAT_FLAT_ANGLED = 'airline_seat_flat_angled',
    PHONE_BLUETOOTH_SPEAKER = 'phone_bluetooth_speaker',
    DIRECTIONS_OFF = 'directions_off',
    AIRLINE_SEAT_LEGROOM_NORMAL = 'airline_seat_legroom_normal',
    AIRLINE_SEAT_LEGROOM_EXTRA = 'airline_seat_legroom_extra',
    AIRLINE_SEAT_LEGROOM_REDUCED = 'airline_seat_legroom_reduced',
    
    /* Hardware */
    KEYBOARD_ARROW_DOWN = 'keyboard_arrow_down',
    PHONE_IPHONE = 'phone_iphone',
    SMARTPHONE = 'smartphone',
    KEYBOARD_ARROW_RIGHT = 'keyboard_arrow_right',
    COMPUTER = 'computer',
    SECURITY = 'security',
    SMART_DISPLAY = 'smart_display',
    DESKTOP_WINDOWS = 'desktop_windows',
    KEYBOARD_BACKSPACE = 'keyboard_backspace',
    PHONE_ANDROID = 'phone_android',
    KEYBOARD_ARROW_UP = 'keyboard_arrow_up',
    
    LAPTOP = 'laptop',
    KEYBOARD_ARROW_LEFT = 'keyboard_arrow_left',
    SMART_TOY = 'smart_toy',
    HEADPHONES = 'headphones',
    KEYBOARD = 'keyboard',
    KEYBOARD_RETURN = 'keyboard_return',
    MEMORY = 'memory',
    KEYBOARD_DOUBLE_ARROW_RIGHT = 'keyboard_double_arrow_right',
    HEADSET_MIC = 'headset_mic',
    TV = 'tv',
    POINT_OF_SALE = 'point_of_sale',
    
    MOUSE = 'mouse',
    KEYBOARD_DOUBLE_ARROW_LEFT = 'keyboard_double_arrow_left',
    KEYBOARD_VOICE = 'keyboard_voice',
    DEVELOPER_BOARD = 'developer_board',
    KEYBOARD_DOUBLE_ARROW_DOWN = 'keyboard_double_arrow_down',
    VIDEOGAME_ASSET = 'videogame_asset',
    ROUTER = 'router',
    CAST_FOR_EDUCATION = 'cast_for_education',
    DEVICE_HUB = 'device_hub',
    HEADSET = 'headset',
    LAPTOP_MAC = 'laptop_mac',
    
    CAST = 'cast',
    KEYBOARD_DOUBLE_ARROW_UP = 'keyboard_double_arrow_up',
    WATCH = 'watch',
    START = 'start',
    TABLET_MAC = 'tablet_mac',
    DEVICES_OTHER = 'devices_other',
    DESKTOP_MAC = 'desktop_mac',
    KEYBOARD_TAB = 'keyboard_tab',
    LAPTOP_CHROMEBOOK = 'laptop_chromebook',
    PHONELINK = 'phonelink',
    MONITOR = 'monitor',
    
    SPEAKER = 'speaker',
    TOYS = 'toys',
    GAMEPAD = 'gamepad',
    SIM_CARD = 'sim_card',
    KEYBOARD_ALT = 'keyboard_alt',
    CONNECTED_TV = 'connected_tv',
    TABLET_ANDROID = 'tablet_android',
    CAST_CONNECTED = 'cast_connected',
    LAPTOP_WINDOWS = 'laptop_windows',
    DEVICE_UNKNOWN = 'device_unknown',
    KEYBOARD_HIDE = 'keyboard_hide',
    
    SCANNER = 'scanner',
    BROWSER_UPDATED = 'browser_updated',
    TABLET = 'tablet',
    KEYBOARD_CAPSLOCK = 'keyboard_capslock',
    SPEAKER_GROUP = 'speaker_group',
    EARBUDS = 'earbuds',
    HEADSET_OFF = 'headset_off',
    HOME_MAX = 'home_max',
    HEADPHONES_BATTERY = 'headphones_battery',
    SMART_SCREEN = 'smart_screen',
    POWER_INPUT = 'power_input',
    
    DOCK = 'dock',
    BROWSER_NOT_SUPPORTED = 'browser_not_supported',
    KEYBOARD_COMMAND_KEY = 'keyboard_command_key',
    EARBUDS_BATTERY = 'earbuds_battery',
    HOME_MINI = 'home_mini',
    PHONELINK_OFF = 'phonelink_off',
    DEVELOPER_BOARD_OFF = 'developer_board_off',
    VIDEOGAME_ASSET_OFF = 'videogame_asset_off',
    ADF_SCANNER = 'adf_scanner',
    KEYBOARD_CONTROL_KEY = 'keyboard_control_key',
    WATCH_OFF = 'watch_off',
    KEYBOARD_OPTION_KEY = 'keyboard_option_key',
    
    /* Device */
    LIGHT_MODE = 'light_mode',
    RESTART_ALT = 'restart_alt',
    DARK_MODE = 'dark_mode',
    TASK = 'task',
    SUMMARIZE = 'summarize',
    PASSWORD = 'password',
    SELL = 'sell',
    SIGNAL_CELLULAR_ALT = 'signal_cellular_alt',
    DEVICES = 'devices',
    SETTINGS_SUGGEST = 'settings_suggest',
    QUIZ = 'quiz',
    
    WIDGETS = 'widgets',
    STORAGE = 'storage',
    THERMOSTAT = 'thermostat',
    BATTERY_FULL = 'battery_full',
    CREDIT_SCORE = 'credit_score',
    GPS_FIXED = 'gps_fixed',
    MEDICATION = 'medication',
    PRICE_CHECK = 'price_check',
    PIN = 'pin',
    GPP_GOOD = 'gpp_good',
    PRICE_CHANGE = 'price_change',
    
    TUNGSTEN = 'tungsten',
    BATTERY_CHARGING_FULL = 'battery_charging_full',
    FMD_GOOD = 'fmd_good',
    REVIEWS = 'reviews',
    NOTE_ALT = 'note_alt',
    AIR = 'air',
    GRAPHIC_EQ = 'graphic_eq',
    BLUETOOTH = 'bluetooth',
    DVR = 'dvr',
    NIGHTLIGHT = 'nightlight',
    SPORTS_SCORE = 'sports_score',
    
    ACCESS_TIME = 'access_time',
    WATER = 'water',
    MONITOR_HEART = 'monitor_heart',
    SHARE_LOCATION = 'share_location',
    GPP_MAYBE = 'gpp_maybe',
    CABLE = 'cable',
    LOCATION_SEARCHING = 'location_searching',
    CAMERASWITCH = 'cameraswitch',
    SHORTCUT = 'shortcut',
    DEVICE_THERMOSTAT = 'device_thermostat',
    AIRPLANE_TICKET = 'airplane_ticket',
    
    WALLPAPER = 'wallpaper',
    RADAR = 'radar',
    DATA_USAGE = 'data_usage',
    MONITOR_WEIGHT = 'monitor_weight',
    SIGNAL_WIFI_4_BAR = 'signal_wifi_4_bar',
    GPP_BAD = 'gpp_bad',
    DEVELOPER_MODE = 'developer_mode',
    BATTERY_STD = 'battery_std',
    MODE_NIGHT = 'mode_night',
    WIFI_TETHERING = 'wifi_tethering',
    BLOODTYPE = 'bloodtype',
    
    SIGNAL_CELLULAR_4_BAR = 'signal_cellular_4_bar',
    FLASHLIGHT_ON = 'flashlight_on',
    NETWORK_WIFI = 'network_wifi',
    FMD_BAD = 'fmd_bad',
    SPLITSCREEN = 'splitscreen',
    AIRPLANEMODE_ACTIVE = 'airplanemode_active',
    ACCESS_TIME_FILLED = 'access_time_filled',
    MOBILE_FRIENDLY = 'mobile_friendly',
    SIM_CARD_DOWNLOAD = 'sim_card_download',
    BATTERY_ALERT = 'battery_alert',
    SEND_TO_MOBILE = 'send_to_mobile',
    
    SCREEN_SEARCH_DESKTOP = 'screen_search_desktop',
    USB = 'usb',
    DISCOUNT = 'discount',
    LENS_BLUR = 'lens_blur',
    SIGNAL_WIFI_STATUSBAR_4_BAR = 'signal_wifi_statusbar_4_bar',
    SCREEN_ROTATION = 'screen_rotation',
    SIGNAL_WIFI_STATUSBAR_CONNECTED_NO_INTERNET_4 = 'signal_wifi_statusbar_connected_no_internet_4',
    SYSTEM_SECURITY_UPDATE_GOOD = 'system_security_update_good',
    GPS_NOT_FIXED = 'gps_not_fixed',
    BLUETOOTH_CONNECTED = 'bluetooth_connected',
    REMEMBER_ME = 'remember_me',
    
    PATTERN = 'pattern',
    LAN = 'lan',
    NFC = 'nfc',
    BRIGHTNESS_HIGH = 'brightness_high',
    MODE_STANDBY = 'mode_standby',
    BATTERY_SAVER = 'battery_saver',
    PLAY_LESSON = 'play_lesson',
    STORM = 'storm',
    DATA_SAVER_OFF = 'data_saver_off',
    NETWORK_CELL = 'network_cell',
    SCREENSHOT = 'screenshot',
    
    BRIGHTNESS_MEDIUM = 'brightness_medium',
    SIGNAL_WIFI_0_BAR = 'signal_wifi_0_bar',
    BRIGHTNESS_LOW = 'brightness_low',
    DATA_SAVER_ON = 'data_saver_on',
    BLUETOOTH_SEARCHING = 'bluetooth_searching',
    GRID_4X4 = 'grid_4x4',
    MOBILEDATA_OFF = 'mobiledata_off',
    AD_UNITS = 'ad_units',
    BLUETOOTH_DISABLED = 'bluetooth_disabled',
    SECURITY_UPDATE_GOOD = 'security_update_good',
    HDR_AUTO = 'hdr_auto',
    
    BATTERY_UNKNOWN = 'battery_unknown',
    SIGNAL_WIFI_OFF = 'signal_wifi_off',
    SIGNAL_WIFI_BAD = 'signal_wifi_bad',
    SETTINGS_SYSTEM_DAYDREAM = 'settings_system_daydream',
    BATTERY_5_BAR = 'battery_5_bar',
    WIFI_CALLING_3 = 'wifi_calling_3',
    ACCESS_ALARMS = 'access_alarms',
    SIGNAL_WIFI_CONNECTED_NO_INTERNET_4 = 'signal_wifi_connected_no_internet_4',
    AOD = 'aod',
    ADD_TO_HOME_SCREEN = 'add_to_home_screen',
    SSID_CHART = 'ssid_chart',
    
    SECURITY_UPDATE = 'security_update',
    SIGNAL_CELLULAR_0_BAR = 'signal_cellular_0_bar',
    FLASHLIGHT_OFF = 'flashlight_off',
    ACCESS_ALARM = 'access_alarm',
    GPS_OFF = 'gps_off',
    QUATRE_G_MOBILEDATA = '4g_mobiledata',
    BATTERY_4_BAR = 'battery_4_bar',
    GRID_3X3 = 'grid_3x3',
    SIGNAL_WIFI_STATUSBAR_NULL = 'signal_wifi_statusbar_null',
    BATTERY_0_BAR = 'battery_0_bar',
    SD_STORAGE = 'sd_storage',
    
    BATTERY_6_BAR = 'battery_6_bar',
    RESET_TV = 'reset_tv',
    WIFI_LOCK = 'wifi_lock',
    BRIGHTNESS_AUTO = 'brightness_auto',
    DO_NOT_DISTURB_ON_TOTAL_SILENCE = 'do_not_disturb_on_total_silence',
    SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_4_BAR = 'signal_cellular_connected_no_internet_4_bar',
    AIRPLANEMODE_INACTIVE = 'airplanemode_inactive',
    UN_X_MOBILEDATA = '1x_mobiledata',
    NEARBY_ERROR = 'nearby_error',
    SECURITY_UPDATE_WARNING = 'security_update_warning',
    SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_0_BAR = 'signal_cellular_connected_no_internet_0_bar',
    
    BATTERY_3_BAR = 'battery_3_bar',
    SCREEN_LOCK_PORTRAIT = 'screen_lock_portrait',
    SYSTEM_SECURITY_UPDATE = 'system_security_update',
    SYSTEM_SECURITY_UPDATE_WARNING = 'system_security_update_warning',
    WIFI_TETHERING_OFF = 'wifi_tethering_off',
    PUNCH_CLOCK = 'punch_clock',
    EDGESENSOR_HIGH = 'edgesensor_high',
    BATTERY_1_BAR = 'battery_1_bar',
    QUATRE_G_PLUS_MOBILEDATA = '4g_plus_mobiledata',
    SIGNAL_WIFI_4_BAR_LOCK = 'signal_wifi_4_bar_lock',
    SIGNAL_CELLULAR_OFF = 'signal_cellular_off',
    
    WIFI_PASSWORD = 'wifi_password',
    LTE_MOBILEDATA = 'lte_mobiledata',
    SIGNAL_CELLULAR_NODATA = 'signal_cellular_nodata',
    ADD_ALARM = 'add_alarm',
    MEDIA_BLUETOOTH_ON = 'media_bluetooth_on',
    BLUETOOTH_DRIVE = 'bluetooth_drive',
    MEDICATION_LIQUID = 'medication_liquid',
    LOCATION_DISABLED = 'location_disabled',
    SIGNAL_CELLULAR_NULL = 'signal_cellular_null',
    MOBILE_OFF = 'mobile_off',
    BATTERY_2_BAR = 'battery_2_bar',
    
    TRENTE_FPS = '30fps',
    GRID_GOLDENRATIO = 'grid_goldenratio',
    RSVP = 'rsvp',
    SCREEN_LOCK_ROTATION = 'screen_lock_rotation',
    EDGESENSOR_LOW = 'edgesensor_low',
    TROIS_G_MOBILEDATA = '3g_mobiledata',
    SOIXANTE_FPS = '60fps',
    PHISHING = 'phishing',
    SCREEN_LOCK_LANDSCAPE = 'screen_lock_landscape',
    LTE_PLUS_MOBILEDATA = 'lte_plus_mobiledata',
    USB_OFF = 'usb_off',
    
    TIMER_10_SELECT = 'timer_10_select',
    SCREENSHOT_MONITOR = 'screenshot_monitor',
    SIGNAL_CELLULAR_NO_SIM = 'signal_cellular_no_sim',
    G_MOBILEDATA = 'g_mobiledata',
    WIFI_FIND = 'wifi_find',
    TIMER_3_SELECT = 'timer_3_select',
    NETWORK_WIFI_1_BAR = 'network_wifi_1_bar',
    NETWORK_WIFI_3_BAR = 'network_wifi_3_bar',
    H_MOBILEDATA = 'h_mobiledata',
    MEDIA_BLUETOOTH_OFF = 'media_bluetooth_off',
    E_MOBILEDATA = 'e_mobiledata',
    
    R_MOBILEDATA = 'r_mobiledata',
    WIFI_TETHERING_ERROR = 'wifi_tethering_error',
    H_PLUS_MOBILEDATA = 'h_plus_mobiledata',
    HDR_ON_SELECT = 'hdr_on_select',
    NETWORK_WIFI_2_BAR = 'network_wifi_2_bar',
    WIFI_CHANNEL = 'wifi_channel',
    HDR_AUTO_SELECT = 'hdr_auto_select',
    WIFI_2_BAR = 'wifi_2_bar',
    SIGNAL_CELLULAR_ALT_2_BAR = 'signal_cellular_alt_2_bar',
    NEARBY_OFF = 'nearby_off',
    HDR_OFF_SELECT = 'hdr_off_select',
    
    SIGNAL_CELLULAR_ALT_1_BAR = 'signal_cellular_alt_1_bar',
    WIFI_1_BAR = 'wifi_1_bar',
    DEVICES_FOLD = 'devices_fold',
    DATASET = 'dataset',
    DATASET_LINKED = 'dataset_linked',
    MACRO_OFF = 'macro_off',
    FLUORESCENT = 'fluorescent',
    
    /* Places */
    STOREFRONT = 'storefront',
    APARTMENT = 'apartment',
    FITNESS_CENTER = 'fitness_center',
    BUSINESS_CENTER = 'business_center',
    SPA = 'spa',
    HOUSE = 'house',
    MEETING_ROOM = 'meeting_room',
    CORPORATE_FARE = 'corporate_fare',
    AC_UNIT = 'ac_unit',
    COTTAGE = 'cottage',
    FAMILY_RESTROOM = 'family_restroom',
    
    OTHER_HOUSES = 'other_houses',
    CHECKROOM = 'checkroom',
    GRASS = 'grass',
    ALL_INCLUSIVE = 'all_inclusive',
    AIRPORT_SHUTTLE = 'airport_shuttle',
    CHILD_CARE = 'child_care',
    BEACH_ACCESS = 'beach_access',
    POOL = 'pool',
    KITCHEN = 'kitchen',
    HOLIDAY_VILLAGE = 'holiday_village',
    CASINO = 'casino',
    
    ROOFING = 'roofing',
    ROOM_SERVICE = 'room_service',
    ROOM_PREFERENCES = 'room_preferences',
    SPORTS_BAR = 'sports_bar',
    BATHTUB = 'bathtub',
    FREE_BREAKFAST = 'free_breakfast',
    ESCALATOR_WARNING = 'escalator_warning',
    CHILD_FRIENDLY = 'child_friendly',
    FOUNDATION = 'foundation',
    FOOD_BANK = 'food_bank',
    GITE = 'gite',
    
    VILLA = 'villa',
    NIGHT_SHELTER = 'night_shelter',
    GOLF_COURSE = 'golf_course',
    MICROWAVE = 'microwave',
    STAIRS = 'stairs',
    NO_PHOTOGRAPHY = 'no_photography',
    BACKPACK = 'backpack',
    ELEVATOR = 'elevator',
    WASH = 'wash',
    SMOKING_ROOMS = 'smoking_rooms',
    CABIN = 'cabin',
    
    HOUSE_SIDING = 'house_siding',
    HOT_TUB = 'hot_tub',
    COUNTERTOPS = 'countertops',
    WATER_DAMAGE = 'water_damage',
    FIRE_EXTINGUISHER = 'fire_extinguisher',
    CARPENTER = 'carpenter',
    CHARGING_STATION = 'charging_station',
    SOAP = 'soap',
    RV_HOOKUP = 'rv_hookup',
    BABY_CHANGING_STATION = 'baby_changing_station',
    UMBRELLA = 'umbrella',
    
    SMOKE_FREE = 'smoke_free',
    TAPAS = 'tapas',
    RICE_BOWL = 'rice_bowl',
    DO_NOT_TOUCH = 'do_not_touch',
    BALCONY = 'balcony',
    NO_FOOD = 'no_food',
    FENCE = 'fence',
    HOUSEBOAT = 'houseboat',
    TTY = 'tty',
    WHEELCHAIR_PICKUP = 'wheelchair_pickup',
    BENTO = 'bento',
    
    IRON = 'iron',
    BUNGALOW = 'bungalow',
    CHALET = 'chalet',
    CRIB = 'crib',
    NO_MEETING_ROOM = 'no_meeting_room',
    DO_NOT_STEP = 'do_not_step',
    DRY = 'dry',
    ESCALATOR = 'escalator',
    STROLLER = 'stroller',
    NO_DRINKS = 'no_drinks',
    NO_CELL = 'no_cell',
    
    NO_FLASH = 'no_flash',
    NO_BACKPACK = 'no_backpack',
    NO_STROLLER = 'no_stroller',
    VAPING_ROOMS = 'vaping_rooms',
    VAPE_FREE = 'vape_free',
    DESK = 'desk',
    
    /* Search */
    FEED = 'feed',
    MANAGE_SEARCH = 'manage_search',
    CHAIR = 'chair',
    BED = 'bed',
    PODCASTS = 'podcasts',
    SHOWER = 'shower',
    COFFEE = 'coffee',
    YARD = 'yard',
    WINDOW = 'window',
    DOOR_FRONT = 'door_front',
    LIGHT = 'light',
    
    GARAGE = 'garage',
    DINING = 'dining',
    FLATWARE = 'flatware',
    COFFEE_MAKER = 'coffee_maker',
    BLENDER = 'blender',
    CAMERA_INDOOR = 'camera_indoor',
    BEDROOM_PARENT = 'bedroom_parent',
    BATHROOM = 'bathroom',
    BEDROOM_BABY = 'bedroom_baby',
    TABLE_RESTAURANT = 'table_restaurant',
    CHAIR_ALT = 'chair_alt',
    
    DOOR_SLIDING = 'door_sliding',
    DOOR_BACK = 'door_back',
    CAMERA_OUTDOOR = 'camera_outdoor',
    LIVING = 'living',
    DOORBELL = 'doorbell',
    BEDROOM_CHILD = 'bedroom_child',
    TABLE_BAR = 'table_bar',
    
    /* Home */
    SENSOR_DOOR = 'sensor_door',
    SENSOR_WINDOW = 'sensor_window',
    SHIELD_MOON = 'shield_moon',
    ELECTRIC_BOLT = 'electric_bolt',
    ENERGY_SAVINGS_LEAF = 'energy_savings_leaf',
    SOLAR_POWER = 'solar_power',
    AUTO_MODE = 'auto_mode',
    WIND_POWER = 'wind_power',
    OIL_BARREL = 'oil_barrel',
    HEAT_PUMP = 'heat_pump',
    ELECTRIC_METER = 'electric_meter',
    
    GAS_METER = 'gas_meter',
    SENSOR_OCCUPIED = 'sensor_occupied',
    PROPANE_TANK = 'propane_tank',
    MODE_FAN_OFF = 'mode_fan_off',
    ROLLER_SHADES = 'roller_shades',
    PROPANE = 'propane',
    ROLLER_SHADES_CLOSED = 'roller_shades_closed',
    BROADCAST_ON_PERSONAL = 'broadcast_on_personal',
    VERTICAL_SHADES_CLOSED = 'vertical_shades_closed',
    BLINDS_CLOSED = 'blinds_closed',
    VERTICAL_SHADES = 'vertical_shades',
    
    CURTAINS = 'curtains',
    BLINDS = 'blinds',
    CURTAINS_CLOSED = 'curtains_closed',
    NEST_CAM_WIRED_STAND = 'nest_cam_wired_stand',
    BROADCAST_ON_HOME = 'broadcast_on_home',
    
}

export interface IIconProps {
    className?: string;
    icon: EIcon;
    onClick?: {(): void};
    spinning?: boolean;
    style?: any;
    tooltipText?: string;
}

export class Icon extends React.PureComponent<IIconProps, {}> {
    constructor (props: IIconProps) {
        super(props);

        this.handleClick = this.handleClick.bind(this);
    }

    handleClick (): void {
        if (this.props.onClick) {
            this.props.onClick();
        }
    }

    render () {
        let className = Common.getClassName('stk-icon', this.props.className);

        let style = undefined;
        if (this.props.style) {
            style = this.props.style;
        }
        if (this.props.spinning === true) {
            className += ' stk-icon-spinning';
        }
        let icon = (<span className={className} style={style} onClick={this.handleClick}>{this.props.icon}</span>);

        if (this.props.tooltipText) {
            icon = (<Tooltip text={this.props.tooltipText}>{icon}</Tooltip>);
        }
        return icon;
    }
}
